#激活哪一个环境的配置文件
#公共配置
spring:
  profiles:
    active: dev
  application:
    name: admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8200
  connection-timeout: 3000
token:
  name: token
  header: X-Token