package com.odm.oa.dao.pojo;

public class CrmCustomerSource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_source.ID
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_source.SOURCE_CODE
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    private Integer sourceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_source.SOURCE_NAME
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    private String sourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_source.CONTENT
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_source.ID
     *
     * @return the value of crm_customer_source.ID
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_source.ID
     *
     * @param id the value for crm_customer_source.ID
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_source.SOURCE_CODE
     *
     * @return the value of crm_customer_source.SOURCE_CODE
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public Integer getSourceCode() {
        return sourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_source.SOURCE_CODE
     *
     * @param sourceCode the value for crm_customer_source.SOURCE_CODE
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public void setSourceCode(Integer sourceCode) {
        this.sourceCode = sourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_source.SOURCE_NAME
     *
     * @return the value of crm_customer_source.SOURCE_NAME
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_source.SOURCE_NAME
     *
     * @param sourceName the value for crm_customer_source.SOURCE_NAME
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_source.CONTENT
     *
     * @return the value of crm_customer_source.CONTENT
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_source.CONTENT
     *
     * @param content the value for crm_customer_source.CONTENT
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}