package com.odm.oa.dao.pojo;

public class CrmFollowState {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_follow_state.ID
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_follow_state.STATE_CODE
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    private Integer stateCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_follow_state.STATE_NAME
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    private String stateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_follow_state.CONTENT
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_follow_state.ID
     *
     * @return the value of crm_follow_state.ID
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_follow_state.ID
     *
     * @param id the value for crm_follow_state.ID
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_follow_state.STATE_CODE
     *
     * @return the value of crm_follow_state.STATE_CODE
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public Integer getStateCode() {
        return stateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_follow_state.STATE_CODE
     *
     * @param stateCode the value for crm_follow_state.STATE_CODE
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public void setStateCode(Integer stateCode) {
        this.stateCode = stateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_follow_state.STATE_NAME
     *
     * @return the value of crm_follow_state.STATE_NAME
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public String getStateName() {
        return stateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_follow_state.STATE_NAME
     *
     * @param stateName the value for crm_follow_state.STATE_NAME
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_follow_state.CONTENT
     *
     * @return the value of crm_follow_state.CONTENT
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_follow_state.CONTENT
     *
     * @param content the value for crm_follow_state.CONTENT
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}