package com.odm.oa.dao.pojo;

import java.util.Date;

public class FtFileVesion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Vesion.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Vesion.R_FILE_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer rFileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Vesion.VERSION_SM
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String versionSm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Vesion.FILE_MD5
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String fileMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Vesion.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Vesion.FILE_SIZE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Vesion.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Vesion.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Vesion.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Vesion.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Vesion.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Vesion.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Vesion.ID
     *
     * @return the value of FT_File_Vesion.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Vesion.ID
     *
     * @param id the value for FT_File_Vesion.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Vesion.R_FILE_ID
     *
     * @return the value of FT_File_Vesion.R_FILE_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getrFileId() {
        return rFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Vesion.R_FILE_ID
     *
     * @param rFileId the value for FT_File_Vesion.R_FILE_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setrFileId(Integer rFileId) {
        this.rFileId = rFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Vesion.VERSION_SM
     *
     * @return the value of FT_File_Vesion.VERSION_SM
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getVersionSm() {
        return versionSm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Vesion.VERSION_SM
     *
     * @param versionSm the value for FT_File_Vesion.VERSION_SM
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setVersionSm(String versionSm) {
        this.versionSm = versionSm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Vesion.FILE_MD5
     *
     * @return the value of FT_File_Vesion.FILE_MD5
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getFileMd5() {
        return fileMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Vesion.FILE_MD5
     *
     * @param fileMd5 the value for FT_File_Vesion.FILE_MD5
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setFileMd5(String fileMd5) {
        this.fileMd5 = fileMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Vesion.REMARK
     *
     * @return the value of FT_File_Vesion.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Vesion.REMARK
     *
     * @param remark the value for FT_File_Vesion.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Vesion.FILE_SIZE
     *
     * @return the value of FT_File_Vesion.FILE_SIZE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Vesion.FILE_SIZE
     *
     * @param fileSize the value for FT_File_Vesion.FILE_SIZE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Vesion.COM_ID
     *
     * @return the value of FT_File_Vesion.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Vesion.COM_ID
     *
     * @param comId the value for FT_File_Vesion.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Vesion.DEL_FLG
     *
     * @return the value of FT_File_Vesion.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Vesion.DEL_FLG
     *
     * @param delFlg the value for FT_File_Vesion.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Vesion.UP_USER
     *
     * @return the value of FT_File_Vesion.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Vesion.UP_USER
     *
     * @param upUser the value for FT_File_Vesion.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Vesion.UP_DATE
     *
     * @return the value of FT_File_Vesion.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Vesion.UP_DATE
     *
     * @param upDate the value for FT_File_Vesion.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Vesion.CR_USER
     *
     * @return the value of FT_File_Vesion.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Vesion.CR_USER
     *
     * @param crUser the value for FT_File_Vesion.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Vesion.CR_DATE
     *
     * @return the value of FT_File_Vesion.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Vesion.CR_DATE
     *
     * @param crDate the value for FT_File_Vesion.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}