package com.odm.oa.dao.pojo;

import java.util.Date;

public class FtFolder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.FOLDER_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String folderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.P_FOLDER_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer pFolderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.FOLDER_LEV
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer folderLev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.FOLDER_SPACE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String folderSpace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.VIEW_AUTH_USERS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String viewAuthUsers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.DOWNLOAD_AUTH_USERS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String downloadAuthUsers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.UPLOAD_AUTH_USERS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String uploadAuthUsers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.COLLECT_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String collectUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.FOLD_UPLOAD_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String foldUploadUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.FOLD_DOWNLOAD_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String foldDownloadUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.SHARE_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String shareCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.SHARE_PASD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String sharePasd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.SHARE_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String shareType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.SHARE_DUE_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date shareDueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
	private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_Folder.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.ID
     *
     * @return the value of FT_Folder.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.ID
     *
     * @param id the value for FT_Folder.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.NAME
     *
     * @return the value of FT_Folder.NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.NAME
     *
     * @param name the value for FT_Folder.NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.FOLDER_TYPE
     *
     * @return the value of FT_Folder.FOLDER_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getFolderType() {
        return folderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.FOLDER_TYPE
     *
     * @param folderType the value for FT_Folder.FOLDER_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setFolderType(String folderType) {
        this.folderType = folderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.P_FOLDER_ID
     *
     * @return the value of FT_Folder.P_FOLDER_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getpFolderId() {
        return pFolderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.P_FOLDER_ID
     *
     * @param pFolderId the value for FT_Folder.P_FOLDER_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setpFolderId(Integer pFolderId) {
        this.pFolderId = pFolderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.FOLDER_LEV
     *
     * @return the value of FT_Folder.FOLDER_LEV
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getFolderLev() {
        return folderLev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.FOLDER_LEV
     *
     * @param folderLev the value for FT_Folder.FOLDER_LEV
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setFolderLev(Integer folderLev) {
        this.folderLev = folderLev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.REMARK
     *
     * @return the value of FT_Folder.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.REMARK
     *
     * @param remark the value for FT_Folder.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.FOLDER_SPACE
     *
     * @return the value of FT_Folder.FOLDER_SPACE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getFolderSpace() {
        return folderSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.FOLDER_SPACE
     *
     * @param folderSpace the value for FT_Folder.FOLDER_SPACE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setFolderSpace(String folderSpace) {
        this.folderSpace = folderSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.VIEW_AUTH_USERS
     *
     * @return the value of FT_Folder.VIEW_AUTH_USERS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getViewAuthUsers() {
        return viewAuthUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.VIEW_AUTH_USERS
     *
     * @param viewAuthUsers the value for FT_Folder.VIEW_AUTH_USERS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setViewAuthUsers(String viewAuthUsers) {
        this.viewAuthUsers = viewAuthUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.DOWNLOAD_AUTH_USERS
     *
     * @return the value of FT_Folder.DOWNLOAD_AUTH_USERS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDownloadAuthUsers() {
        return downloadAuthUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.DOWNLOAD_AUTH_USERS
     *
     * @param downloadAuthUsers the value for FT_Folder.DOWNLOAD_AUTH_USERS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDownloadAuthUsers(String downloadAuthUsers) {
        this.downloadAuthUsers = downloadAuthUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.UPLOAD_AUTH_USERS
     *
     * @return the value of FT_Folder.UPLOAD_AUTH_USERS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUploadAuthUsers() {
        return uploadAuthUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.UPLOAD_AUTH_USERS
     *
     * @param uploadAuthUsers the value for FT_Folder.UPLOAD_AUTH_USERS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUploadAuthUsers(String uploadAuthUsers) {
        this.uploadAuthUsers = uploadAuthUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.COLLECT_USER
     *
     * @return the value of FT_Folder.COLLECT_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCollectUser() {
        return collectUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.COLLECT_USER
     *
     * @param collectUser the value for FT_Folder.COLLECT_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCollectUser(String collectUser) {
        this.collectUser = collectUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.FOLD_UPLOAD_URL
     *
     * @return the value of FT_Folder.FOLD_UPLOAD_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getFoldUploadUrl() {
        return foldUploadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.FOLD_UPLOAD_URL
     *
     * @param foldUploadUrl the value for FT_Folder.FOLD_UPLOAD_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setFoldUploadUrl(String foldUploadUrl) {
        this.foldUploadUrl = foldUploadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.FOLD_DOWNLOAD_URL
     *
     * @return the value of FT_Folder.FOLD_DOWNLOAD_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getFoldDownloadUrl() {
        return foldDownloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.FOLD_DOWNLOAD_URL
     *
     * @param foldDownloadUrl the value for FT_Folder.FOLD_DOWNLOAD_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setFoldDownloadUrl(String foldDownloadUrl) {
        this.foldDownloadUrl = foldDownloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.SHARE_CODE
     *
     * @return the value of FT_Folder.SHARE_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getShareCode() {
        return shareCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.SHARE_CODE
     *
     * @param shareCode the value for FT_Folder.SHARE_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setShareCode(String shareCode) {
        this.shareCode = shareCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.SHARE_PASD
     *
     * @return the value of FT_Folder.SHARE_PASD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getSharePasd() {
        return sharePasd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.SHARE_PASD
     *
     * @param sharePasd the value for FT_Folder.SHARE_PASD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setSharePasd(String sharePasd) {
        this.sharePasd = sharePasd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.SHARE_TYPE
     *
     * @return the value of FT_Folder.SHARE_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getShareType() {
        return shareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.SHARE_TYPE
     *
     * @param shareType the value for FT_Folder.SHARE_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setShareType(String shareType) {
        this.shareType = shareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.SHARE_DUE_DATE
     *
     * @return the value of FT_Folder.SHARE_DUE_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getShareDueDate() {
        return shareDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.SHARE_DUE_DATE
     *
     * @param shareDueDate the value for FT_Folder.SHARE_DUE_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setShareDueDate(Date shareDueDate) {
        this.shareDueDate = shareDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.COM_ID
     *
     * @return the value of FT_Folder.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.COM_ID
     *
     * @param comId the value for FT_Folder.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.DEL_FLG
     *
     * @return the value of FT_Folder.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
	public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.DEL_FLG
     *
     * @param delFlg the value for FT_Folder.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
	public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.UP_USER
     *
     * @return the value of FT_Folder.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.UP_USER
     *
     * @param upUser the value for FT_Folder.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.UP_DATE
     *
     * @return the value of FT_Folder.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.UP_DATE
     *
     * @param upDate the value for FT_Folder.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.CR_USER
     *
     * @return the value of FT_Folder.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.CR_USER
     *
     * @param crUser the value for FT_Folder.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_Folder.CR_DATE
     *
     * @return the value of FT_Folder.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_Folder.CR_DATE
     *
     * @param crDate the value for FT_Folder.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}