package com.odm.oa.dao.pojo;

import java.util.Date;

public class JhAuthBranch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.DEPT_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.DEPE_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String depeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.DEPT_SHORT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer deptShort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.DEPT_DESC
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String deptDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.DEPT_ROOT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer deptRoot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.BRANCH_LEVEL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer branchLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.REMARK1
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.REMARK2
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String remark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.BRANCH_LEADER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String branchLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.WXBM_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer wxbmCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.TXLQX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String txlqx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.ROLE_QX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String roleQx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.IS_HAS_QX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String isHasQx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.ROOM_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String roomCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Branch.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.DEPT_CODE
     *
     * @return the value of JH_Auth_Branch.DEPT_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.DEPT_CODE
     *
     * @param deptCode the value for JH_Auth_Branch.DEPT_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDeptCode(Integer deptCode) {
        this.deptCode = deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.DEPE_NAME
     *
     * @return the value of JH_Auth_Branch.DEPE_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDepeName() {
        return depeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.DEPE_NAME
     *
     * @param depeName the value for JH_Auth_Branch.DEPE_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDepeName(String depeName) {
        this.depeName = depeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.DEPT_SHORT
     *
     * @return the value of JH_Auth_Branch.DEPT_SHORT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getDeptShort() {
        return deptShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.DEPT_SHORT
     *
     * @param deptShort the value for JH_Auth_Branch.DEPT_SHORT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDeptShort(Integer deptShort) {
        this.deptShort = deptShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.DEPT_DESC
     *
     * @return the value of JH_Auth_Branch.DEPT_DESC
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDeptDesc() {
        return deptDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.DEPT_DESC
     *
     * @param deptDesc the value for JH_Auth_Branch.DEPT_DESC
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDeptDesc(String deptDesc) {
        this.deptDesc = deptDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.DEPT_ROOT
     *
     * @return the value of JH_Auth_Branch.DEPT_ROOT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getDeptRoot() {
        return deptRoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.DEPT_ROOT
     *
     * @param deptRoot the value for JH_Auth_Branch.DEPT_ROOT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDeptRoot(Integer deptRoot) {
        this.deptRoot = deptRoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.BRANCH_LEVEL
     *
     * @return the value of JH_Auth_Branch.BRANCH_LEVEL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getBranchLevel() {
        return branchLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.BRANCH_LEVEL
     *
     * @param branchLevel the value for JH_Auth_Branch.BRANCH_LEVEL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setBranchLevel(Integer branchLevel) {
        this.branchLevel = branchLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.REMARK1
     *
     * @return the value of JH_Auth_Branch.REMARK1
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.REMARK1
     *
     * @param remark1 the value for JH_Auth_Branch.REMARK1
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.REMARK2
     *
     * @return the value of JH_Auth_Branch.REMARK2
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.REMARK2
     *
     * @param remark2 the value for JH_Auth_Branch.REMARK2
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.BRANCH_LEADER
     *
     * @return the value of JH_Auth_Branch.BRANCH_LEADER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getBranchLeader() {
        return branchLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.BRANCH_LEADER
     *
     * @param branchLeader the value for JH_Auth_Branch.BRANCH_LEADER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setBranchLeader(String branchLeader) {
        this.branchLeader = branchLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.WXBM_CODE
     *
     * @return the value of JH_Auth_Branch.WXBM_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getWxbmCode() {
        return wxbmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.WXBM_CODE
     *
     * @param wxbmCode the value for JH_Auth_Branch.WXBM_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setWxbmCode(Integer wxbmCode) {
        this.wxbmCode = wxbmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.TXLQX
     *
     * @return the value of JH_Auth_Branch.TXLQX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getTxlqx() {
        return txlqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.TXLQX
     *
     * @param txlqx the value for JH_Auth_Branch.TXLQX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setTxlqx(String txlqx) {
        this.txlqx = txlqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.ROLE_QX
     *
     * @return the value of JH_Auth_Branch.ROLE_QX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRoleQx() {
        return roleQx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.ROLE_QX
     *
     * @param roleQx the value for JH_Auth_Branch.ROLE_QX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRoleQx(String roleQx) {
        this.roleQx = roleQx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.IS_HAS_QX
     *
     * @return the value of JH_Auth_Branch.IS_HAS_QX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getIsHasQx() {
        return isHasQx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.IS_HAS_QX
     *
     * @param isHasQx the value for JH_Auth_Branch.IS_HAS_QX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsHasQx(String isHasQx) {
        this.isHasQx = isHasQx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.ROOM_CODE
     *
     * @return the value of JH_Auth_Branch.ROOM_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRoomCode() {
        return roomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.ROOM_CODE
     *
     * @param roomCode the value for JH_Auth_Branch.ROOM_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRoomCode(String roomCode) {
        this.roomCode = roomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.COM_ID
     *
     * @return the value of JH_Auth_Branch.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.COM_ID
     *
     * @param comId the value for JH_Auth_Branch.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.DEL_FLG
     *
     * @return the value of JH_Auth_Branch.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.DEL_FLG
     *
     * @param delFlg the value for JH_Auth_Branch.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.UP_USER
     *
     * @return the value of JH_Auth_Branch.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.UP_USER
     *
     * @param upUser the value for JH_Auth_Branch.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.UP_DATE
     *
     * @return the value of JH_Auth_Branch.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.UP_DATE
     *
     * @param upDate the value for JH_Auth_Branch.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.CR_USER
     *
     * @return the value of JH_Auth_Branch.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.CR_USER
     *
     * @param crUser the value for JH_Auth_Branch.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Branch.CR_DATE
     *
     * @return the value of JH_Auth_Branch.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Branch.CR_DATE
     *
     * @param crDate the value for JH_Auth_Branch.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}