package com.odm.oa.dao.pojo;

import java.util.Date;

public class JhAuthQyModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_Model.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_Model.MODEL_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_Model.STATUS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_Model.PDID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer pdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_Model.AGENT_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_Model.QY_MODEL_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String qyModelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_Model.MODEL_ADMIN
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String modelAdmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_Model.IS_INIT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer isInit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_Model.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_Model.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_Model.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_Model.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_Model.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_Model.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_Model.ID
     *
     * @return the value of JH_Auth_QY_Model.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_Model.ID
     *
     * @param id the value for JH_Auth_QY_Model.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_Model.MODEL_ID
     *
     * @return the value of JH_Auth_QY_Model.MODEL_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_Model.MODEL_ID
     *
     * @param modelId the value for JH_Auth_QY_Model.MODEL_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_Model.STATUS
     *
     * @return the value of JH_Auth_QY_Model.STATUS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_Model.STATUS
     *
     * @param status the value for JH_Auth_QY_Model.STATUS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_Model.PDID
     *
     * @return the value of JH_Auth_QY_Model.PDID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getPdid() {
        return pdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_Model.PDID
     *
     * @param pdid the value for JH_Auth_QY_Model.PDID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setPdid(Integer pdid) {
        this.pdid = pdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_Model.AGENT_ID
     *
     * @return the value of JH_Auth_QY_Model.AGENT_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_Model.AGENT_ID
     *
     * @param agentId the value for JH_Auth_QY_Model.AGENT_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setAgentId(String agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_Model.QY_MODEL_CODE
     *
     * @return the value of JH_Auth_QY_Model.QY_MODEL_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getQyModelCode() {
        return qyModelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_Model.QY_MODEL_CODE
     *
     * @param qyModelCode the value for JH_Auth_QY_Model.QY_MODEL_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setQyModelCode(String qyModelCode) {
        this.qyModelCode = qyModelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_Model.MODEL_ADMIN
     *
     * @return the value of JH_Auth_QY_Model.MODEL_ADMIN
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getModelAdmin() {
        return modelAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_Model.MODEL_ADMIN
     *
     * @param modelAdmin the value for JH_Auth_QY_Model.MODEL_ADMIN
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setModelAdmin(String modelAdmin) {
        this.modelAdmin = modelAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_Model.IS_INIT
     *
     * @return the value of JH_Auth_QY_Model.IS_INIT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getIsInit() {
        return isInit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_Model.IS_INIT
     *
     * @param isInit the value for JH_Auth_QY_Model.IS_INIT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsInit(Integer isInit) {
        this.isInit = isInit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_Model.COM_ID
     *
     * @return the value of JH_Auth_QY_Model.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_Model.COM_ID
     *
     * @param comId the value for JH_Auth_QY_Model.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_Model.DEL_FLG
     *
     * @return the value of JH_Auth_QY_Model.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_Model.DEL_FLG
     *
     * @param delFlg the value for JH_Auth_QY_Model.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_Model.UP_USER
     *
     * @return the value of JH_Auth_QY_Model.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_Model.UP_USER
     *
     * @param upUser the value for JH_Auth_QY_Model.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_Model.UP_DATE
     *
     * @return the value of JH_Auth_QY_Model.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_Model.UP_DATE
     *
     * @param upDate the value for JH_Auth_QY_Model.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_Model.CR_USER
     *
     * @return the value of JH_Auth_QY_Model.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_Model.CR_USER
     *
     * @param crUser the value for JH_Auth_QY_Model.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_Model.CR_DATE
     *
     * @return the value of JH_Auth_QY_Model.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_Model.CR_DATE
     *
     * @param crDate the value for JH_Auth_QY_Model.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}