package com.odm.oa.dao.pojo;

import java.util.Date;

public class JhAuthUserCenter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.USER_TO
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String userTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.USER_FROM
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String userFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.MSG_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.MSG_MODE_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String msgModeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.MSG_CONTENT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String msgContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.IS_SEND
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer isSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.DATA_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.MSG_LINK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String msgLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.WX_LINK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String wxLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.READ_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date readDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.IS_READ
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.IS_CS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String isCs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User_Center.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.ID
     *
     * @return the value of JH_Auth_User_Center.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.ID
     *
     * @param id the value for JH_Auth_User_Center.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.USER_TO
     *
     * @return the value of JH_Auth_User_Center.USER_TO
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUserTo() {
        return userTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.USER_TO
     *
     * @param userTo the value for JH_Auth_User_Center.USER_TO
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUserTo(String userTo) {
        this.userTo = userTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.USER_FROM
     *
     * @return the value of JH_Auth_User_Center.USER_FROM
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUserFrom() {
        return userFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.USER_FROM
     *
     * @param userFrom the value for JH_Auth_User_Center.USER_FROM
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUserFrom(String userFrom) {
        this.userFrom = userFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.MSG_TYPE
     *
     * @return the value of JH_Auth_User_Center.MSG_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.MSG_TYPE
     *
     * @param msgType the value for JH_Auth_User_Center.MSG_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setMsgType(String msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.MSG_MODE_ID
     *
     * @return the value of JH_Auth_User_Center.MSG_MODE_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getMsgModeId() {
        return msgModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.MSG_MODE_ID
     *
     * @param msgModeId the value for JH_Auth_User_Center.MSG_MODE_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setMsgModeId(String msgModeId) {
        this.msgModeId = msgModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.MSG_CONTENT
     *
     * @return the value of JH_Auth_User_Center.MSG_CONTENT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.MSG_CONTENT
     *
     * @param msgContent the value for JH_Auth_User_Center.MSG_CONTENT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.IS_SEND
     *
     * @return the value of JH_Auth_User_Center.IS_SEND
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getIsSend() {
        return isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.IS_SEND
     *
     * @param isSend the value for JH_Auth_User_Center.IS_SEND
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsSend(Integer isSend) {
        this.isSend = isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.DATA_ID
     *
     * @return the value of JH_Auth_User_Center.DATA_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.DATA_ID
     *
     * @param dataId the value for JH_Auth_User_Center.DATA_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.MSG_LINK
     *
     * @return the value of JH_Auth_User_Center.MSG_LINK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getMsgLink() {
        return msgLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.MSG_LINK
     *
     * @param msgLink the value for JH_Auth_User_Center.MSG_LINK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setMsgLink(String msgLink) {
        this.msgLink = msgLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.WX_LINK
     *
     * @return the value of JH_Auth_User_Center.WX_LINK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getWxLink() {
        return wxLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.WX_LINK
     *
     * @param wxLink the value for JH_Auth_User_Center.WX_LINK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setWxLink(String wxLink) {
        this.wxLink = wxLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.REMARK
     *
     * @return the value of JH_Auth_User_Center.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.REMARK
     *
     * @param remark the value for JH_Auth_User_Center.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.READ_DATE
     *
     * @return the value of JH_Auth_User_Center.READ_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getReadDate() {
        return readDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.READ_DATE
     *
     * @param readDate the value for JH_Auth_User_Center.READ_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setReadDate(Date readDate) {
        this.readDate = readDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.IS_READ
     *
     * @return the value of JH_Auth_User_Center.IS_READ
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.IS_READ
     *
     * @param isRead the value for JH_Auth_User_Center.IS_READ
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.IS_CS
     *
     * @return the value of JH_Auth_User_Center.IS_CS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getIsCs() {
        return isCs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.IS_CS
     *
     * @param isCs the value for JH_Auth_User_Center.IS_CS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsCs(String isCs) {
        this.isCs = isCs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.COM_ID
     *
     * @return the value of JH_Auth_User_Center.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.COM_ID
     *
     * @param comId the value for JH_Auth_User_Center.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.DEL_FLG
     *
     * @return the value of JH_Auth_User_Center.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.DEL_FLG
     *
     * @param delFlg the value for JH_Auth_User_Center.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.UP_USER
     *
     * @return the value of JH_Auth_User_Center.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.UP_USER
     *
     * @param upUser the value for JH_Auth_User_Center.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.UP_DATE
     *
     * @return the value of JH_Auth_User_Center.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.UP_DATE
     *
     * @param upDate the value for JH_Auth_User_Center.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.CR_USER
     *
     * @return the value of JH_Auth_User_Center.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.CR_USER
     *
     * @param crUser the value for JH_Auth_User_Center.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User_Center.CR_DATE
     *
     * @return the value of JH_Auth_User_Center.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User_Center.CR_DATE
     *
     * @param crDate the value for JH_Auth_User_Center.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}