package com.odm.oa.dao.pojo;

import java.util.Date;

public class JhAuthUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.USER_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.USER_REAL_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String userRealName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.USER_PASS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String userPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.BRANCH_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer branchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.SEX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.IS_USE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String isUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.STATUS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.USERSIGN
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String usersign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.TELPHONE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.MOBPHONE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String mobphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.TX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String tx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.ZHIWU
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String zhiwu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.REMARK1
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.MAILBOX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String mailbox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.WEIXINNUM
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String weixinnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.PCCODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String pccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.PCCODEUPDATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date pccodeupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.MOBCODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String mobcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.MOBCODEDATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date mobcodedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.USER_LEADER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String userLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.USER_LOGO_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer userLogoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.USER_ORDER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer userOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.TXURL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String txurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.ISGZ
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String isgz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.LOGINDATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date logindate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.IS_SUP_ADMIN
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String isSupAdmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.TXLQX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String txlqx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.ROLE_QX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String roleQx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.ROOM_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String roomCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.USER_GW
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String userGw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.NICK_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.JOB_NUM
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String jobNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.QQ
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.ID_CARD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.NATIONALITY
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.NATION
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.HOME_ADDRESS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String homeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.GS_PHONE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String gsPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.ENTRY_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date entryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.DEPARTURE_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date departureDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.BIRTHDAY
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.MARRIAGE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String marriage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.CHILDREN
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String children;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.JJLXR
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String jjlxr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.JJLXRDH
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String jjlxrdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.HIRE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String hire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.ZZ_TIME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date zzTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.CONTRACT_S_TIME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date contractSTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.CONTRACT_E_TIME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date contractETime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.SOCIAL_INSURANCE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String socialInsurance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.GJJID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String gjjid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.BANK_CARD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String bankCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.BANK_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.WEIXIN_CARD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String weixinCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.IS_SHOW_YD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer isShowYd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.FILES
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String files;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_User.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.ID
     *
     * @return the value of JH_Auth_User.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.ID
     *
     * @param id the value for JH_Auth_User.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.USER_NAME
     *
     * @return the value of JH_Auth_User.USER_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.USER_NAME
     *
     * @param userName the value for JH_Auth_User.USER_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.USER_REAL_NAME
     *
     * @return the value of JH_Auth_User.USER_REAL_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUserRealName() {
        return userRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.USER_REAL_NAME
     *
     * @param userRealName the value for JH_Auth_User.USER_REAL_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUserRealName(String userRealName) {
        this.userRealName = userRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.USER_PASS
     *
     * @return the value of JH_Auth_User.USER_PASS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUserPass() {
        return userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.USER_PASS
     *
     * @param userPass the value for JH_Auth_User.USER_PASS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.BRANCH_CODE
     *
     * @return the value of JH_Auth_User.BRANCH_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getBranchCode() {
        return branchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.BRANCH_CODE
     *
     * @param branchCode the value for JH_Auth_User.BRANCH_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setBranchCode(Integer branchCode) {
        this.branchCode = branchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.SEX
     *
     * @return the value of JH_Auth_User.SEX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.SEX
     *
     * @param sex the value for JH_Auth_User.SEX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.IS_USE
     *
     * @return the value of JH_Auth_User.IS_USE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.IS_USE
     *
     * @param isUse the value for JH_Auth_User.IS_USE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsUse(String isUse) {
        this.isUse = isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.STATUS
     *
     * @return the value of JH_Auth_User.STATUS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.STATUS
     *
     * @param status the value for JH_Auth_User.STATUS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.USERSIGN
     *
     * @return the value of JH_Auth_User.USERSIGN
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUsersign() {
        return usersign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.USERSIGN
     *
     * @param usersign the value for JH_Auth_User.USERSIGN
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUsersign(String usersign) {
        this.usersign = usersign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.TELPHONE
     *
     * @return the value of JH_Auth_User.TELPHONE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.TELPHONE
     *
     * @param telphone the value for JH_Auth_User.TELPHONE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.MOBPHONE
     *
     * @return the value of JH_Auth_User.MOBPHONE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getMobphone() {
        return mobphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.MOBPHONE
     *
     * @param mobphone the value for JH_Auth_User.MOBPHONE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setMobphone(String mobphone) {
        this.mobphone = mobphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.TX
     *
     * @return the value of JH_Auth_User.TX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getTx() {
        return tx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.TX
     *
     * @param tx the value for JH_Auth_User.TX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setTx(String tx) {
        this.tx = tx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.ZHIWU
     *
     * @return the value of JH_Auth_User.ZHIWU
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getZhiwu() {
        return zhiwu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.ZHIWU
     *
     * @param zhiwu the value for JH_Auth_User.ZHIWU
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setZhiwu(String zhiwu) {
        this.zhiwu = zhiwu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.REMARK
     *
     * @return the value of JH_Auth_User.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.REMARK
     *
     * @param remark the value for JH_Auth_User.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.REMARK1
     *
     * @return the value of JH_Auth_User.REMARK1
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.REMARK1
     *
     * @param remark1 the value for JH_Auth_User.REMARK1
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRemark1(Integer remark1) {
        this.remark1 = remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.MAILBOX
     *
     * @return the value of JH_Auth_User.MAILBOX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getMailbox() {
        return mailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.MAILBOX
     *
     * @param mailbox the value for JH_Auth_User.MAILBOX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setMailbox(String mailbox) {
        this.mailbox = mailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.WEIXINNUM
     *
     * @return the value of JH_Auth_User.WEIXINNUM
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getWeixinnum() {
        return weixinnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.WEIXINNUM
     *
     * @param weixinnum the value for JH_Auth_User.WEIXINNUM
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setWeixinnum(String weixinnum) {
        this.weixinnum = weixinnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.PCCODE
     *
     * @return the value of JH_Auth_User.PCCODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getPccode() {
        return pccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.PCCODE
     *
     * @param pccode the value for JH_Auth_User.PCCODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setPccode(String pccode) {
        this.pccode = pccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.PCCODEUPDATE
     *
     * @return the value of JH_Auth_User.PCCODEUPDATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getPccodeupdate() {
        return pccodeupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.PCCODEUPDATE
     *
     * @param pccodeupdate the value for JH_Auth_User.PCCODEUPDATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setPccodeupdate(Date pccodeupdate) {
        this.pccodeupdate = pccodeupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.MOBCODE
     *
     * @return the value of JH_Auth_User.MOBCODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getMobcode() {
        return mobcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.MOBCODE
     *
     * @param mobcode the value for JH_Auth_User.MOBCODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setMobcode(String mobcode) {
        this.mobcode = mobcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.MOBCODEDATE
     *
     * @return the value of JH_Auth_User.MOBCODEDATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getMobcodedate() {
        return mobcodedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.MOBCODEDATE
     *
     * @param mobcodedate the value for JH_Auth_User.MOBCODEDATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setMobcodedate(Date mobcodedate) {
        this.mobcodedate = mobcodedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.COM_ID
     *
     * @return the value of JH_Auth_User.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.COM_ID
     *
     * @param comId the value for JH_Auth_User.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.USER_LEADER
     *
     * @return the value of JH_Auth_User.USER_LEADER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUserLeader() {
        return userLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.USER_LEADER
     *
     * @param userLeader the value for JH_Auth_User.USER_LEADER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUserLeader(String userLeader) {
        this.userLeader = userLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.USER_LOGO_ID
     *
     * @return the value of JH_Auth_User.USER_LOGO_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getUserLogoId() {
        return userLogoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.USER_LOGO_ID
     *
     * @param userLogoId the value for JH_Auth_User.USER_LOGO_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUserLogoId(Integer userLogoId) {
        this.userLogoId = userLogoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.USER_ORDER
     *
     * @return the value of JH_Auth_User.USER_ORDER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getUserOrder() {
        return userOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.USER_ORDER
     *
     * @param userOrder the value for JH_Auth_User.USER_ORDER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUserOrder(Integer userOrder) {
        this.userOrder = userOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.TXURL
     *
     * @return the value of JH_Auth_User.TXURL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getTxurl() {
        return txurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.TXURL
     *
     * @param txurl the value for JH_Auth_User.TXURL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setTxurl(String txurl) {
        this.txurl = txurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.ISGZ
     *
     * @return the value of JH_Auth_User.ISGZ
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getIsgz() {
        return isgz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.ISGZ
     *
     * @param isgz the value for JH_Auth_User.ISGZ
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsgz(String isgz) {
        this.isgz = isgz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.LOGINDATE
     *
     * @return the value of JH_Auth_User.LOGINDATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getLogindate() {
        return logindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.LOGINDATE
     *
     * @param logindate the value for JH_Auth_User.LOGINDATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setLogindate(Date logindate) {
        this.logindate = logindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.IS_SUP_ADMIN
     *
     * @return the value of JH_Auth_User.IS_SUP_ADMIN
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getIsSupAdmin() {
        return isSupAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.IS_SUP_ADMIN
     *
     * @param isSupAdmin the value for JH_Auth_User.IS_SUP_ADMIN
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsSupAdmin(String isSupAdmin) {
        this.isSupAdmin = isSupAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.TXLQX
     *
     * @return the value of JH_Auth_User.TXLQX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getTxlqx() {
        return txlqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.TXLQX
     *
     * @param txlqx the value for JH_Auth_User.TXLQX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setTxlqx(String txlqx) {
        this.txlqx = txlqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.ROLE_QX
     *
     * @return the value of JH_Auth_User.ROLE_QX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRoleQx() {
        return roleQx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.ROLE_QX
     *
     * @param roleQx the value for JH_Auth_User.ROLE_QX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRoleQx(String roleQx) {
        this.roleQx = roleQx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.ROOM_CODE
     *
     * @return the value of JH_Auth_User.ROOM_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRoomCode() {
        return roomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.ROOM_CODE
     *
     * @param roomCode the value for JH_Auth_User.ROOM_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRoomCode(String roomCode) {
        this.roomCode = roomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.USER_GW
     *
     * @return the value of JH_Auth_User.USER_GW
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUserGw() {
        return userGw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.USER_GW
     *
     * @param userGw the value for JH_Auth_User.USER_GW
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUserGw(String userGw) {
        this.userGw = userGw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.NICK_NAME
     *
     * @return the value of JH_Auth_User.NICK_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.NICK_NAME
     *
     * @param nickName the value for JH_Auth_User.NICK_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.JOB_NUM
     *
     * @return the value of JH_Auth_User.JOB_NUM
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getJobNum() {
        return jobNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.JOB_NUM
     *
     * @param jobNum the value for JH_Auth_User.JOB_NUM
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setJobNum(String jobNum) {
        this.jobNum = jobNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.QQ
     *
     * @return the value of JH_Auth_User.QQ
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.QQ
     *
     * @param qq the value for JH_Auth_User.QQ
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.ID_CARD
     *
     * @return the value of JH_Auth_User.ID_CARD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.ID_CARD
     *
     * @param idCard the value for JH_Auth_User.ID_CARD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.NATIONALITY
     *
     * @return the value of JH_Auth_User.NATIONALITY
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.NATIONALITY
     *
     * @param nationality the value for JH_Auth_User.NATIONALITY
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.NATION
     *
     * @return the value of JH_Auth_User.NATION
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.NATION
     *
     * @param nation the value for JH_Auth_User.NATION
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.HOME_ADDRESS
     *
     * @return the value of JH_Auth_User.HOME_ADDRESS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.HOME_ADDRESS
     *
     * @param homeAddress the value for JH_Auth_User.HOME_ADDRESS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.GS_PHONE
     *
     * @return the value of JH_Auth_User.GS_PHONE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getGsPhone() {
        return gsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.GS_PHONE
     *
     * @param gsPhone the value for JH_Auth_User.GS_PHONE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setGsPhone(String gsPhone) {
        this.gsPhone = gsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.ENTRY_DATE
     *
     * @return the value of JH_Auth_User.ENTRY_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.ENTRY_DATE
     *
     * @param entryDate the value for JH_Auth_User.ENTRY_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.DEPARTURE_DATE
     *
     * @return the value of JH_Auth_User.DEPARTURE_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getDepartureDate() {
        return departureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.DEPARTURE_DATE
     *
     * @param departureDate the value for JH_Auth_User.DEPARTURE_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDepartureDate(Date departureDate) {
        this.departureDate = departureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.BIRTHDAY
     *
     * @return the value of JH_Auth_User.BIRTHDAY
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.BIRTHDAY
     *
     * @param birthday the value for JH_Auth_User.BIRTHDAY
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.MARRIAGE
     *
     * @return the value of JH_Auth_User.MARRIAGE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getMarriage() {
        return marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.MARRIAGE
     *
     * @param marriage the value for JH_Auth_User.MARRIAGE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setMarriage(String marriage) {
        this.marriage = marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.CHILDREN
     *
     * @return the value of JH_Auth_User.CHILDREN
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getChildren() {
        return children;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.CHILDREN
     *
     * @param children the value for JH_Auth_User.CHILDREN
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setChildren(String children) {
        this.children = children;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.JJLXR
     *
     * @return the value of JH_Auth_User.JJLXR
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getJjlxr() {
        return jjlxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.JJLXR
     *
     * @param jjlxr the value for JH_Auth_User.JJLXR
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setJjlxr(String jjlxr) {
        this.jjlxr = jjlxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.JJLXRDH
     *
     * @return the value of JH_Auth_User.JJLXRDH
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getJjlxrdh() {
        return jjlxrdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.JJLXRDH
     *
     * @param jjlxrdh the value for JH_Auth_User.JJLXRDH
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setJjlxrdh(String jjlxrdh) {
        this.jjlxrdh = jjlxrdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.HIRE
     *
     * @return the value of JH_Auth_User.HIRE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getHire() {
        return hire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.HIRE
     *
     * @param hire the value for JH_Auth_User.HIRE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setHire(String hire) {
        this.hire = hire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.ZZ_TIME
     *
     * @return the value of JH_Auth_User.ZZ_TIME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getZzTime() {
        return zzTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.ZZ_TIME
     *
     * @param zzTime the value for JH_Auth_User.ZZ_TIME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setZzTime(Date zzTime) {
        this.zzTime = zzTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.CONTRACT_S_TIME
     *
     * @return the value of JH_Auth_User.CONTRACT_S_TIME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getContractSTime() {
        return contractSTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.CONTRACT_S_TIME
     *
     * @param contractSTime the value for JH_Auth_User.CONTRACT_S_TIME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setContractSTime(Date contractSTime) {
        this.contractSTime = contractSTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.CONTRACT_E_TIME
     *
     * @return the value of JH_Auth_User.CONTRACT_E_TIME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getContractETime() {
        return contractETime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.CONTRACT_E_TIME
     *
     * @param contractETime the value for JH_Auth_User.CONTRACT_E_TIME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setContractETime(Date contractETime) {
        this.contractETime = contractETime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.SOCIAL_INSURANCE
     *
     * @return the value of JH_Auth_User.SOCIAL_INSURANCE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getSocialInsurance() {
        return socialInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.SOCIAL_INSURANCE
     *
     * @param socialInsurance the value for JH_Auth_User.SOCIAL_INSURANCE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setSocialInsurance(String socialInsurance) {
        this.socialInsurance = socialInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.GJJID
     *
     * @return the value of JH_Auth_User.GJJID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getGjjid() {
        return gjjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.GJJID
     *
     * @param gjjid the value for JH_Auth_User.GJJID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setGjjid(String gjjid) {
        this.gjjid = gjjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.BANK_CARD
     *
     * @return the value of JH_Auth_User.BANK_CARD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getBankCard() {
        return bankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.BANK_CARD
     *
     * @param bankCard the value for JH_Auth_User.BANK_CARD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setBankCard(String bankCard) {
        this.bankCard = bankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.BANK_NAME
     *
     * @return the value of JH_Auth_User.BANK_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.BANK_NAME
     *
     * @param bankName the value for JH_Auth_User.BANK_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.WEIXIN_CARD
     *
     * @return the value of JH_Auth_User.WEIXIN_CARD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getWeixinCard() {
        return weixinCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.WEIXIN_CARD
     *
     * @param weixinCard the value for JH_Auth_User.WEIXIN_CARD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setWeixinCard(String weixinCard) {
        this.weixinCard = weixinCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.IS_SHOW_YD
     *
     * @return the value of JH_Auth_User.IS_SHOW_YD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getIsShowYd() {
        return isShowYd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.IS_SHOW_YD
     *
     * @param isShowYd the value for JH_Auth_User.IS_SHOW_YD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsShowYd(Integer isShowYd) {
        this.isShowYd = isShowYd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.FILES
     *
     * @return the value of JH_Auth_User.FILES
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getFiles() {
        return files;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.FILES
     *
     * @param files the value for JH_Auth_User.FILES
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setFiles(String files) {
        this.files = files;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.DEL_FLG
     *
     * @return the value of JH_Auth_User.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.DEL_FLG
     *
     * @param delFlg the value for JH_Auth_User.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.UP_USER
     *
     * @return the value of JH_Auth_User.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.UP_USER
     *
     * @param upUser the value for JH_Auth_User.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.UP_DATE
     *
     * @return the value of JH_Auth_User.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.UP_DATE
     *
     * @param upDate the value for JH_Auth_User.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.CR_USER
     *
     * @return the value of JH_Auth_User.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.CR_USER
     *
     * @param crUser the value for JH_Auth_User.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_User.CR_DATE
     *
     * @return the value of JH_Auth_User.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_User.CR_DATE
     *
     * @param crDate the value for JH_Auth_User.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}