package com.odm.oa.dao.pojo;

import java.util.Date;

public class JhAuthCommon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Common.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Common.TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Common.MENU_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String menuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Common.MENU_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Common.URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Common.URL1
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String url1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Common.URL2
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String url2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Common.MODEL_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String modelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Common.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Common.SORT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Common.TOP_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer topId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Common.STATUS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Common.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Common.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Common.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Common.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Common.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Common.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Common.ID
     *
     * @return the value of JH_Auth_Common.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Common.ID
     *
     * @param id the value for JH_Auth_Common.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Common.TYPE
     *
     * @return the value of JH_Auth_Common.TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Common.TYPE
     *
     * @param type the value for JH_Auth_Common.TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Common.MENU_CODE
     *
     * @return the value of JH_Auth_Common.MENU_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Common.MENU_CODE
     *
     * @param menuCode the value for JH_Auth_Common.MENU_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Common.MENU_NAME
     *
     * @return the value of JH_Auth_Common.MENU_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Common.MENU_NAME
     *
     * @param menuName the value for JH_Auth_Common.MENU_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Common.URL
     *
     * @return the value of JH_Auth_Common.URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Common.URL
     *
     * @param url the value for JH_Auth_Common.URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Common.URL1
     *
     * @return the value of JH_Auth_Common.URL1
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUrl1() {
        return url1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Common.URL1
     *
     * @param url1 the value for JH_Auth_Common.URL1
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUrl1(String url1) {
        this.url1 = url1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Common.URL2
     *
     * @return the value of JH_Auth_Common.URL2
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUrl2() {
        return url2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Common.URL2
     *
     * @param url2 the value for JH_Auth_Common.URL2
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUrl2(String url2) {
        this.url2 = url2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Common.MODEL_CODE
     *
     * @return the value of JH_Auth_Common.MODEL_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getModelCode() {
        return modelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Common.MODEL_CODE
     *
     * @param modelCode the value for JH_Auth_Common.MODEL_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setModelCode(String modelCode) {
        this.modelCode = modelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Common.REMARK
     *
     * @return the value of JH_Auth_Common.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Common.REMARK
     *
     * @param remark the value for JH_Auth_Common.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Common.SORT
     *
     * @return the value of JH_Auth_Common.SORT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Common.SORT
     *
     * @param sort the value for JH_Auth_Common.SORT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setSort(String sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Common.TOP_ID
     *
     * @return the value of JH_Auth_Common.TOP_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getTopId() {
        return topId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Common.TOP_ID
     *
     * @param topId the value for JH_Auth_Common.TOP_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setTopId(Integer topId) {
        this.topId = topId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Common.STATUS
     *
     * @return the value of JH_Auth_Common.STATUS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Common.STATUS
     *
     * @param status the value for JH_Auth_Common.STATUS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Common.COM_ID
     *
     * @return the value of JH_Auth_Common.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Common.COM_ID
     *
     * @param comId the value for JH_Auth_Common.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Common.DEL_FLG
     *
     * @return the value of JH_Auth_Common.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Common.DEL_FLG
     *
     * @param delFlg the value for JH_Auth_Common.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Common.UP_USER
     *
     * @return the value of JH_Auth_Common.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Common.UP_USER
     *
     * @param upUser the value for JH_Auth_Common.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Common.UP_DATE
     *
     * @return the value of JH_Auth_Common.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Common.UP_DATE
     *
     * @param upDate the value for JH_Auth_Common.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Common.CR_USER
     *
     * @return the value of JH_Auth_Common.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Common.CR_USER
     *
     * @param crUser the value for JH_Auth_Common.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Common.CR_DATE
     *
     * @return the value of JH_Auth_Common.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Common.CR_DATE
     *
     * @param crDate the value for JH_Auth_Common.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}