package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.CrmCustomerSource;
import java.util.List;

public interface CrmCustomerSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_source
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_source
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    int insert(CrmCustomerSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_source
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    CrmCustomerSource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_source
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    List<CrmCustomerSource> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_source
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    int updateByPrimaryKey(CrmCustomerSource record);
}