package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.CrmCustomerType;
import java.util.List;

public interface CrmCustomerTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_type
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_type
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    int insert(CrmCustomerType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_type
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    CrmCustomerType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_type
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    List<CrmCustomerType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_type
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    int updateByPrimaryKey(CrmCustomerType record);
}