package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.CrmCustomerIndustry;
import java.util.List;

public interface CrmCustomerIndustryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_industry
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_industry
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    int insert(CrmCustomerIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_industry
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    CrmCustomerIndustry selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_industry
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    List<CrmCustomerIndustry> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_industry
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    int updateByPrimaryKey(CrmCustomerIndustry record);
}