package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.FtFileUserauth;
import java.util.List;

public interface FtFileUserauthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File_UserAuth
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File_UserAuth
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int insert(FtFileUserauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File_UserAuth
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    FtFileUserauth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File_UserAuth
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    List<FtFileUserauth> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File_UserAuth
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int updateByPrimaryKey(FtFileUserauth record);
}