package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.FtFolder;
import java.util.List;

public interface FtFolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_Folder
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_Folder
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int insert(FtFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_Folder
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    FtFolder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_Folder
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    List<FtFolder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_Folder
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int updateByPrimaryKey(FtFolder record);
}