package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.JhAuthExtenddata;
import java.util.List;

public interface JhAuthExtenddataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_ExtendData
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_ExtendData
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int insert(JhAuthExtenddata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_ExtendData
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    JhAuthExtenddata selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_ExtendData
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    List<JhAuthExtenddata> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_ExtendData
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int updateByPrimaryKey(JhAuthExtenddata record);
}