package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.JhAuthFunction;
import java.util.List;

public interface JhAuthFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Function
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Function
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int insert(JhAuthFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Function
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    JhAuthFunction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Function
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    List<JhAuthFunction> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Function
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int updateByPrimaryKey(JhAuthFunction record);
}