package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.JhAuthQy;
import java.util.List;

public interface JhAuthQyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_QY
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int insert(JhAuthQy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_QY
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    List<JhAuthQy> selectAll();
}