package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.JhAuthBranch;
import java.util.List;

public interface JhAuthBranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Branch
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int deleteByPrimaryKey(Integer deptCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Branch
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int insert(JhAuthBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Branch
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    JhAuthBranch selectByPrimaryKey(Integer deptCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Branch
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    List<JhAuthBranch> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Branch
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int updateByPrimaryKey(JhAuthBranch record);
}