package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.JhAuthUserrole;
import java.util.List;

public interface JhAuthUserroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_UserRole
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_UserRole
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int insert(JhAuthUserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_UserRole
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    JhAuthUserrole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_UserRole
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    List<JhAuthUserrole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_UserRole
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    int updateByPrimaryKey(JhAuthUserrole record);
}