package com.odm.oa.dao.pojo;

public class CrmCustomerScale {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_scale.ID
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_scale.SCALE_CODE
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    private Integer scaleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_scale.SCALE_NAME
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    private String scaleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_scale.CONTENT
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_scale.ID
     *
     * @return the value of crm_customer_scale.ID
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_scale.ID
     *
     * @param id the value for crm_customer_scale.ID
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_scale.SCALE_CODE
     *
     * @return the value of crm_customer_scale.SCALE_CODE
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public Integer getScaleCode() {
        return scaleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_scale.SCALE_CODE
     *
     * @param scaleCode the value for crm_customer_scale.SCALE_CODE
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public void setScaleCode(Integer scaleCode) {
        this.scaleCode = scaleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_scale.SCALE_NAME
     *
     * @return the value of crm_customer_scale.SCALE_NAME
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public String getScaleName() {
        return scaleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_scale.SCALE_NAME
     *
     * @param scaleName the value for crm_customer_scale.SCALE_NAME
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public void setScaleName(String scaleName) {
        this.scaleName = scaleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_scale.CONTENT
     *
     * @return the value of crm_customer_scale.CONTENT
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_scale.CONTENT
     *
     * @param content the value for crm_customer_scale.CONTENT
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}