package com.odm.oa.dao.pojo;

public class CrmCustomerIndustry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_industry.ID
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_industry.IN_CODE
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    private Integer inCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_industry.IN_NAME
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    private String inName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_industry.CONTENT
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_industry.ID
     *
     * @return the value of crm_customer_industry.ID
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_industry.ID
     *
     * @param id the value for crm_customer_industry.ID
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_industry.IN_CODE
     *
     * @return the value of crm_customer_industry.IN_CODE
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public Integer getInCode() {
        return inCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_industry.IN_CODE
     *
     * @param inCode the value for crm_customer_industry.IN_CODE
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public void setInCode(Integer inCode) {
        this.inCode = inCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_industry.IN_NAME
     *
     * @return the value of crm_customer_industry.IN_NAME
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public String getInName() {
        return inName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_industry.IN_NAME
     *
     * @param inName the value for crm_customer_industry.IN_NAME
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public void setInName(String inName) {
        this.inName = inName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_industry.CONTENT
     *
     * @return the value of crm_customer_industry.CONTENT
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_industry.CONTENT
     *
     * @param content the value for crm_customer_industry.CONTENT
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}