package com.odm.oa.dao.pojo;

import java.util.Date;

public class FtFileShare {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Share.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Share.REF_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer refId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Share.REF_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String refType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Share.SHARE_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String shareUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Share.SHARE_PASD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String sharePasd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Share.SHARE_DUE_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date shareDueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Share.SHARE_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String shareType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Share.AUTH_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String authType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Share.CR_USER_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Share.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Share.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Share.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Share.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Share.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_Share.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Share.ID
     *
     * @return the value of FT_File_Share.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Share.ID
     *
     * @param id the value for FT_File_Share.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Share.REF_ID
     *
     * @return the value of FT_File_Share.REF_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Share.REF_ID
     *
     * @param refId the value for FT_File_Share.REF_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRefId(Integer refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Share.REF_TYPE
     *
     * @return the value of FT_File_Share.REF_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRefType() {
        return refType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Share.REF_TYPE
     *
     * @param refType the value for FT_File_Share.REF_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRefType(String refType) {
        this.refType = refType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Share.SHARE_URL
     *
     * @return the value of FT_File_Share.SHARE_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getShareUrl() {
        return shareUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Share.SHARE_URL
     *
     * @param shareUrl the value for FT_File_Share.SHARE_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setShareUrl(String shareUrl) {
        this.shareUrl = shareUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Share.SHARE_PASD
     *
     * @return the value of FT_File_Share.SHARE_PASD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getSharePasd() {
        return sharePasd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Share.SHARE_PASD
     *
     * @param sharePasd the value for FT_File_Share.SHARE_PASD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setSharePasd(String sharePasd) {
        this.sharePasd = sharePasd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Share.SHARE_DUE_DATE
     *
     * @return the value of FT_File_Share.SHARE_DUE_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getShareDueDate() {
        return shareDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Share.SHARE_DUE_DATE
     *
     * @param shareDueDate the value for FT_File_Share.SHARE_DUE_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setShareDueDate(Date shareDueDate) {
        this.shareDueDate = shareDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Share.SHARE_TYPE
     *
     * @return the value of FT_File_Share.SHARE_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getShareType() {
        return shareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Share.SHARE_TYPE
     *
     * @param shareType the value for FT_File_Share.SHARE_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setShareType(String shareType) {
        this.shareType = shareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Share.AUTH_TYPE
     *
     * @return the value of FT_File_Share.AUTH_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Share.AUTH_TYPE
     *
     * @param authType the value for FT_File_Share.AUTH_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setAuthType(String authType) {
        this.authType = authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Share.CR_USER_NAME
     *
     * @return the value of FT_File_Share.CR_USER_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUserName() {
        return crUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Share.CR_USER_NAME
     *
     * @param crUserName the value for FT_File_Share.CR_USER_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUserName(String crUserName) {
        this.crUserName = crUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Share.COM_ID
     *
     * @return the value of FT_File_Share.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Share.COM_ID
     *
     * @param comId the value for FT_File_Share.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Share.DEL_FLG
     *
     * @return the value of FT_File_Share.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Share.DEL_FLG
     *
     * @param delFlg the value for FT_File_Share.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Share.UP_USER
     *
     * @return the value of FT_File_Share.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Share.UP_USER
     *
     * @param upUser the value for FT_File_Share.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Share.UP_DATE
     *
     * @return the value of FT_File_Share.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Share.UP_DATE
     *
     * @param upDate the value for FT_File_Share.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Share.CR_USER
     *
     * @return the value of FT_File_Share.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Share.CR_USER
     *
     * @param crUser the value for FT_File_Share.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_Share.CR_DATE
     *
     * @return the value of FT_File_Share.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_Share.CR_DATE
     *
     * @param crDate the value for FT_File_Share.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}