package com.odm.oa.dao.pojo;

import java.util.Date;

public class FtFileUsertag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_UserTag.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_UserTag.REF_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer refId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_UserTag.TAG_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_UserTag.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_UserTag.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_UserTag.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_UserTag.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_UserTag.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File_UserTag.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_UserTag.ID
     *
     * @return the value of FT_File_UserTag.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_UserTag.ID
     *
     * @param id the value for FT_File_UserTag.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_UserTag.REF_ID
     *
     * @return the value of FT_File_UserTag.REF_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_UserTag.REF_ID
     *
     * @param refId the value for FT_File_UserTag.REF_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRefId(Integer refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_UserTag.TAG_NAME
     *
     * @return the value of FT_File_UserTag.TAG_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_UserTag.TAG_NAME
     *
     * @param tagName the value for FT_File_UserTag.TAG_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_UserTag.COM_ID
     *
     * @return the value of FT_File_UserTag.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_UserTag.COM_ID
     *
     * @param comId the value for FT_File_UserTag.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_UserTag.DEL_FLG
     *
     * @return the value of FT_File_UserTag.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_UserTag.DEL_FLG
     *
     * @param delFlg the value for FT_File_UserTag.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_UserTag.UP_USER
     *
     * @return the value of FT_File_UserTag.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_UserTag.UP_USER
     *
     * @param upUser the value for FT_File_UserTag.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_UserTag.UP_DATE
     *
     * @return the value of FT_File_UserTag.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_UserTag.UP_DATE
     *
     * @param upDate the value for FT_File_UserTag.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_UserTag.CR_USER
     *
     * @return the value of FT_File_UserTag.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_UserTag.CR_USER
     *
     * @param crUser the value for FT_File_UserTag.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File_UserTag.CR_DATE
     *
     * @return the value of FT_File_UserTag.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File_UserTag.CR_DATE
     *
     * @param crDate the value for FT_File_UserTag.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}