package com.odm.oa.dao.pojo;

import java.util.Date;

public class FtFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.FOLDER_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer folderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.FILE_EXTEND_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String fileExtendName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.FILE_SIZE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.FILE_DOWNLOAD_CISHU
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer fileDownloadCishu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.FILE_MD5
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String fileMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.FILE_VERSION
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer fileVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.IS_RECYCLE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String isRecycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.FILE_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String fileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.VIEW_AUTH_USERS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String viewAuthUsers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.DOWNLOAD_AUTH_USERS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String downloadAuthUsers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.COLLECT_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String collectUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.SHARE_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String shareCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.SHARE_PASD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String sharePasd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.SHARE_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String shareType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.SHARE_DUE_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date shareDueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.ISYL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String isyl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.YL_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String ylUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.YL_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String ylCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.YL_PATH
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String ylPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.YL_COUNT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String ylCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.TB_STATUS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String tbStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.TOTAL_TIME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer totalTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FT_File.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.ID
     *
     * @return the value of FT_File.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.ID
     *
     * @param id the value for FT_File.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.NAME
     *
     * @return the value of FT_File.NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.NAME
     *
     * @param name the value for FT_File.NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.FOLDER_ID
     *
     * @return the value of FT_File.FOLDER_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.FOLDER_ID
     *
     * @param folderId the value for FT_File.FOLDER_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setFolderId(Integer folderId) {
        this.folderId = folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.FILE_EXTEND_NAME
     *
     * @return the value of FT_File.FILE_EXTEND_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getFileExtendName() {
        return fileExtendName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.FILE_EXTEND_NAME
     *
     * @param fileExtendName the value for FT_File.FILE_EXTEND_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setFileExtendName(String fileExtendName) {
        this.fileExtendName = fileExtendName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.FILE_SIZE
     *
     * @return the value of FT_File.FILE_SIZE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.FILE_SIZE
     *
     * @param fileSize the value for FT_File.FILE_SIZE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.FILE_DOWNLOAD_CISHU
     *
     * @return the value of FT_File.FILE_DOWNLOAD_CISHU
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getFileDownloadCishu() {
        return fileDownloadCishu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.FILE_DOWNLOAD_CISHU
     *
     * @param fileDownloadCishu the value for FT_File.FILE_DOWNLOAD_CISHU
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setFileDownloadCishu(Integer fileDownloadCishu) {
        this.fileDownloadCishu = fileDownloadCishu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.FILE_MD5
     *
     * @return the value of FT_File.FILE_MD5
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getFileMd5() {
        return fileMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.FILE_MD5
     *
     * @param fileMd5 the value for FT_File.FILE_MD5
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setFileMd5(String fileMd5) {
        this.fileMd5 = fileMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.FILE_VERSION
     *
     * @return the value of FT_File.FILE_VERSION
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getFileVersion() {
        return fileVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.FILE_VERSION
     *
     * @param fileVersion the value for FT_File.FILE_VERSION
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setFileVersion(Integer fileVersion) {
        this.fileVersion = fileVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.IS_RECYCLE
     *
     * @return the value of FT_File.IS_RECYCLE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getIsRecycle() {
        return isRecycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.IS_RECYCLE
     *
     * @param isRecycle the value for FT_File.IS_RECYCLE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsRecycle(String isRecycle) {
        this.isRecycle = isRecycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.FILE_URL
     *
     * @return the value of FT_File.FILE_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.FILE_URL
     *
     * @param fileUrl the value for FT_File.FILE_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.VIEW_AUTH_USERS
     *
     * @return the value of FT_File.VIEW_AUTH_USERS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getViewAuthUsers() {
        return viewAuthUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.VIEW_AUTH_USERS
     *
     * @param viewAuthUsers the value for FT_File.VIEW_AUTH_USERS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setViewAuthUsers(String viewAuthUsers) {
        this.viewAuthUsers = viewAuthUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.DOWNLOAD_AUTH_USERS
     *
     * @return the value of FT_File.DOWNLOAD_AUTH_USERS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDownloadAuthUsers() {
        return downloadAuthUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.DOWNLOAD_AUTH_USERS
     *
     * @param downloadAuthUsers the value for FT_File.DOWNLOAD_AUTH_USERS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDownloadAuthUsers(String downloadAuthUsers) {
        this.downloadAuthUsers = downloadAuthUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.COLLECT_USER
     *
     * @return the value of FT_File.COLLECT_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCollectUser() {
        return collectUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.COLLECT_USER
     *
     * @param collectUser the value for FT_File.COLLECT_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCollectUser(String collectUser) {
        this.collectUser = collectUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.SHARE_CODE
     *
     * @return the value of FT_File.SHARE_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getShareCode() {
        return shareCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.SHARE_CODE
     *
     * @param shareCode the value for FT_File.SHARE_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setShareCode(String shareCode) {
        this.shareCode = shareCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.SHARE_PASD
     *
     * @return the value of FT_File.SHARE_PASD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getSharePasd() {
        return sharePasd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.SHARE_PASD
     *
     * @param sharePasd the value for FT_File.SHARE_PASD
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setSharePasd(String sharePasd) {
        this.sharePasd = sharePasd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.SHARE_TYPE
     *
     * @return the value of FT_File.SHARE_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getShareType() {
        return shareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.SHARE_TYPE
     *
     * @param shareType the value for FT_File.SHARE_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setShareType(String shareType) {
        this.shareType = shareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.SHARE_DUE_DATE
     *
     * @return the value of FT_File.SHARE_DUE_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getShareDueDate() {
        return shareDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.SHARE_DUE_DATE
     *
     * @param shareDueDate the value for FT_File.SHARE_DUE_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setShareDueDate(Date shareDueDate) {
        this.shareDueDate = shareDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.ISYL
     *
     * @return the value of FT_File.ISYL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getIsyl() {
        return isyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.ISYL
     *
     * @param isyl the value for FT_File.ISYL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsyl(String isyl) {
        this.isyl = isyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.REMARK
     *
     * @return the value of FT_File.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.REMARK
     *
     * @param remark the value for FT_File.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.YL_URL
     *
     * @return the value of FT_File.YL_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getYlUrl() {
        return ylUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.YL_URL
     *
     * @param ylUrl the value for FT_File.YL_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setYlUrl(String ylUrl) {
        this.ylUrl = ylUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.YL_CODE
     *
     * @return the value of FT_File.YL_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getYlCode() {
        return ylCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.YL_CODE
     *
     * @param ylCode the value for FT_File.YL_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setYlCode(String ylCode) {
        this.ylCode = ylCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.YL_PATH
     *
     * @return the value of FT_File.YL_PATH
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getYlPath() {
        return ylPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.YL_PATH
     *
     * @param ylPath the value for FT_File.YL_PATH
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setYlPath(String ylPath) {
        this.ylPath = ylPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.YL_COUNT
     *
     * @return the value of FT_File.YL_COUNT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getYlCount() {
        return ylCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.YL_COUNT
     *
     * @param ylCount the value for FT_File.YL_COUNT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setYlCount(String ylCount) {
        this.ylCount = ylCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.TB_STATUS
     *
     * @return the value of FT_File.TB_STATUS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getTbStatus() {
        return tbStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.TB_STATUS
     *
     * @param tbStatus the value for FT_File.TB_STATUS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setTbStatus(String tbStatus) {
        this.tbStatus = tbStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.TOTAL_TIME
     *
     * @return the value of FT_File.TOTAL_TIME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getTotalTime() {
        return totalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.TOTAL_TIME
     *
     * @param totalTime the value for FT_File.TOTAL_TIME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setTotalTime(Integer totalTime) {
        this.totalTime = totalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.COM_ID
     *
     * @return the value of FT_File.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.COM_ID
     *
     * @param comId the value for FT_File.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.DEL_FLG
     *
     * @return the value of FT_File.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.DEL_FLG
     *
     * @param delFlg the value for FT_File.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.UP_USER
     *
     * @return the value of FT_File.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.UP_USER
     *
     * @param upUser the value for FT_File.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.UP_DATE
     *
     * @return the value of FT_File.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.UP_DATE
     *
     * @param upDate the value for FT_File.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.CR_USER
     *
     * @return the value of FT_File.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.CR_USER
     *
     * @param crUser the value for FT_File.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FT_File.CR_DATE
     *
     * @return the value of FT_File.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FT_File.CR_DATE
     *
     * @param crDate the value for FT_File.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}