package com.odm.oa.dao.pojo;

import java.util.Date;

public class JhAuthUsercustomdata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_UserCustomData.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_UserCustomData.USER_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_UserCustomData.DATA_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_UserCustomData.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_UserCustomData.DATA_CONTENT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String dataContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_UserCustomData.DATA_CONTENT1
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String dataContent1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_UserCustomData.WXBQ_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer wxbqCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_UserCustomData.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_UserCustomData.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_UserCustomData.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_UserCustomData.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_UserCustomData.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_UserCustomData.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_UserCustomData.ID
     *
     * @return the value of JH_Auth_UserCustomData.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_UserCustomData.ID
     *
     * @param id the value for JH_Auth_UserCustomData.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_UserCustomData.USER_NAME
     *
     * @return the value of JH_Auth_UserCustomData.USER_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_UserCustomData.USER_NAME
     *
     * @param userName the value for JH_Auth_UserCustomData.USER_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_UserCustomData.DATA_TYPE
     *
     * @return the value of JH_Auth_UserCustomData.DATA_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_UserCustomData.DATA_TYPE
     *
     * @param dataType the value for JH_Auth_UserCustomData.DATA_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_UserCustomData.REMARK
     *
     * @return the value of JH_Auth_UserCustomData.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_UserCustomData.REMARK
     *
     * @param remark the value for JH_Auth_UserCustomData.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_UserCustomData.DATA_CONTENT
     *
     * @return the value of JH_Auth_UserCustomData.DATA_CONTENT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDataContent() {
        return dataContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_UserCustomData.DATA_CONTENT
     *
     * @param dataContent the value for JH_Auth_UserCustomData.DATA_CONTENT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDataContent(String dataContent) {
        this.dataContent = dataContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_UserCustomData.DATA_CONTENT1
     *
     * @return the value of JH_Auth_UserCustomData.DATA_CONTENT1
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDataContent1() {
        return dataContent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_UserCustomData.DATA_CONTENT1
     *
     * @param dataContent1 the value for JH_Auth_UserCustomData.DATA_CONTENT1
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDataContent1(String dataContent1) {
        this.dataContent1 = dataContent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_UserCustomData.WXBQ_CODE
     *
     * @return the value of JH_Auth_UserCustomData.WXBQ_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getWxbqCode() {
        return wxbqCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_UserCustomData.WXBQ_CODE
     *
     * @param wxbqCode the value for JH_Auth_UserCustomData.WXBQ_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setWxbqCode(Integer wxbqCode) {
        this.wxbqCode = wxbqCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_UserCustomData.COM_ID
     *
     * @return the value of JH_Auth_UserCustomData.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_UserCustomData.COM_ID
     *
     * @param comId the value for JH_Auth_UserCustomData.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_UserCustomData.DEL_FLG
     *
     * @return the value of JH_Auth_UserCustomData.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_UserCustomData.DEL_FLG
     *
     * @param delFlg the value for JH_Auth_UserCustomData.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_UserCustomData.UP_USER
     *
     * @return the value of JH_Auth_UserCustomData.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_UserCustomData.UP_USER
     *
     * @param upUser the value for JH_Auth_UserCustomData.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_UserCustomData.UP_DATE
     *
     * @return the value of JH_Auth_UserCustomData.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_UserCustomData.UP_DATE
     *
     * @param upDate the value for JH_Auth_UserCustomData.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_UserCustomData.CR_USER
     *
     * @return the value of JH_Auth_UserCustomData.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_UserCustomData.CR_USER
     *
     * @param crUser the value for JH_Auth_UserCustomData.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_UserCustomData.CR_DATE
     *
     * @return the value of JH_Auth_UserCustomData.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_UserCustomData.CR_DATE
     *
     * @param crDate the value for JH_Auth_UserCustomData.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}