package com.odm.oa.dao.pojo;

import java.util.Date;

public class JhAuthRolefun {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_RoleFun.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_RoleFun.ROLE_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_RoleFun.FUN_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer funCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_RoleFun.ACTION_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String actionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_RoleFun.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_RoleFun.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_RoleFun.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_RoleFun.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_RoleFun.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_RoleFun.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_RoleFun.ID
     *
     * @return the value of JH_Auth_RoleFun.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_RoleFun.ID
     *
     * @param id the value for JH_Auth_RoleFun.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_RoleFun.ROLE_CODE
     *
     * @return the value of JH_Auth_RoleFun.ROLE_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_RoleFun.ROLE_CODE
     *
     * @param roleCode the value for JH_Auth_RoleFun.ROLE_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRoleCode(Integer roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_RoleFun.FUN_CODE
     *
     * @return the value of JH_Auth_RoleFun.FUN_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getFunCode() {
        return funCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_RoleFun.FUN_CODE
     *
     * @param funCode the value for JH_Auth_RoleFun.FUN_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setFunCode(Integer funCode) {
        this.funCode = funCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_RoleFun.ACTION_CODE
     *
     * @return the value of JH_Auth_RoleFun.ACTION_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getActionCode() {
        return actionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_RoleFun.ACTION_CODE
     *
     * @param actionCode the value for JH_Auth_RoleFun.ACTION_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setActionCode(String actionCode) {
        this.actionCode = actionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_RoleFun.COM_ID
     *
     * @return the value of JH_Auth_RoleFun.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_RoleFun.COM_ID
     *
     * @param comId the value for JH_Auth_RoleFun.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_RoleFun.DEL_FLG
     *
     * @return the value of JH_Auth_RoleFun.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_RoleFun.DEL_FLG
     *
     * @param delFlg the value for JH_Auth_RoleFun.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_RoleFun.UP_USER
     *
     * @return the value of JH_Auth_RoleFun.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_RoleFun.UP_USER
     *
     * @param upUser the value for JH_Auth_RoleFun.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_RoleFun.UP_DATE
     *
     * @return the value of JH_Auth_RoleFun.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_RoleFun.UP_DATE
     *
     * @param upDate the value for JH_Auth_RoleFun.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_RoleFun.CR_USER
     *
     * @return the value of JH_Auth_RoleFun.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_RoleFun.CR_USER
     *
     * @param crUser the value for JH_Auth_RoleFun.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_RoleFun.CR_DATE
     *
     * @return the value of JH_Auth_RoleFun.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_RoleFun.CR_DATE
     *
     * @param crDate the value for JH_Auth_RoleFun.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}