package com.odm.oa.dao.pojo;

import java.util.Date;

public class JhAuthModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.MODEL_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String modelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.MODEL_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String modelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.REMARK1
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.TJ_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String tjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.MODEL_STATUS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String modelStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.MODE_PIC_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String modePicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.APP_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.MODEL_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String modelUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.IS_SQ
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String isSq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.MODEL_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String modelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.REL_TABLE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String relTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.APP_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String appType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.FILES
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String files;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.ORDERID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.IS_SYS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer isSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.WX_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String wxUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.IS_KJFS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer isKjfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.P_MODEL_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String pModelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.TOKEN
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.ENCODING_AES_KEY
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String encodingAesKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Model.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.ID
     *
     * @return the value of JH_Auth_Model.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.ID
     *
     * @param id the value for JH_Auth_Model.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.MODEL_NAME
     *
     * @return the value of JH_Auth_Model.MODEL_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.MODEL_NAME
     *
     * @param modelName the value for JH_Auth_Model.MODEL_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.MODEL_TYPE
     *
     * @return the value of JH_Auth_Model.MODEL_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getModelType() {
        return modelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.MODEL_TYPE
     *
     * @param modelType the value for JH_Auth_Model.MODEL_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setModelType(String modelType) {
        this.modelType = modelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.REMARK1
     *
     * @return the value of JH_Auth_Model.REMARK1
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.REMARK1
     *
     * @param remark1 the value for JH_Auth_Model.REMARK1
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.TJ_ID
     *
     * @return the value of JH_Auth_Model.TJ_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getTjId() {
        return tjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.TJ_ID
     *
     * @param tjId the value for JH_Auth_Model.TJ_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setTjId(String tjId) {
        this.tjId = tjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.MODEL_STATUS
     *
     * @return the value of JH_Auth_Model.MODEL_STATUS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getModelStatus() {
        return modelStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.MODEL_STATUS
     *
     * @param modelStatus the value for JH_Auth_Model.MODEL_STATUS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setModelStatus(String modelStatus) {
        this.modelStatus = modelStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.MODE_PIC_URL
     *
     * @return the value of JH_Auth_Model.MODE_PIC_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getModePicUrl() {
        return modePicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.MODE_PIC_URL
     *
     * @param modePicUrl the value for JH_Auth_Model.MODE_PIC_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setModePicUrl(String modePicUrl) {
        this.modePicUrl = modePicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.APP_ID
     *
     * @return the value of JH_Auth_Model.APP_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.APP_ID
     *
     * @param appId the value for JH_Auth_Model.APP_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.MODEL_URL
     *
     * @return the value of JH_Auth_Model.MODEL_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getModelUrl() {
        return modelUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.MODEL_URL
     *
     * @param modelUrl the value for JH_Auth_Model.MODEL_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setModelUrl(String modelUrl) {
        this.modelUrl = modelUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.IS_SQ
     *
     * @return the value of JH_Auth_Model.IS_SQ
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getIsSq() {
        return isSq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.IS_SQ
     *
     * @param isSq the value for JH_Auth_Model.IS_SQ
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsSq(String isSq) {
        this.isSq = isSq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.MODEL_CODE
     *
     * @return the value of JH_Auth_Model.MODEL_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getModelCode() {
        return modelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.MODEL_CODE
     *
     * @param modelCode the value for JH_Auth_Model.MODEL_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setModelCode(String modelCode) {
        this.modelCode = modelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.REL_TABLE
     *
     * @return the value of JH_Auth_Model.REL_TABLE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRelTable() {
        return relTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.REL_TABLE
     *
     * @param relTable the value for JH_Auth_Model.REL_TABLE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRelTable(String relTable) {
        this.relTable = relTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.APP_TYPE
     *
     * @return the value of JH_Auth_Model.APP_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.APP_TYPE
     *
     * @param appType the value for JH_Auth_Model.APP_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setAppType(String appType) {
        this.appType = appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.FILES
     *
     * @return the value of JH_Auth_Model.FILES
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getFiles() {
        return files;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.FILES
     *
     * @param files the value for JH_Auth_Model.FILES
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setFiles(String files) {
        this.files = files;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.ORDERID
     *
     * @return the value of JH_Auth_Model.ORDERID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.ORDERID
     *
     * @param orderid the value for JH_Auth_Model.ORDERID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.IS_SYS
     *
     * @return the value of JH_Auth_Model.IS_SYS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getIsSys() {
        return isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.IS_SYS
     *
     * @param isSys the value for JH_Auth_Model.IS_SYS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsSys(Integer isSys) {
        this.isSys = isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.WX_URL
     *
     * @return the value of JH_Auth_Model.WX_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getWxUrl() {
        return wxUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.WX_URL
     *
     * @param wxUrl the value for JH_Auth_Model.WX_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setWxUrl(String wxUrl) {
        this.wxUrl = wxUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.IS_KJFS
     *
     * @return the value of JH_Auth_Model.IS_KJFS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getIsKjfs() {
        return isKjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.IS_KJFS
     *
     * @param isKjfs the value for JH_Auth_Model.IS_KJFS
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsKjfs(Integer isKjfs) {
        this.isKjfs = isKjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.P_MODEL_CODE
     *
     * @return the value of JH_Auth_Model.P_MODEL_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getpModelCode() {
        return pModelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.P_MODEL_CODE
     *
     * @param pModelCode the value for JH_Auth_Model.P_MODEL_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setpModelCode(String pModelCode) {
        this.pModelCode = pModelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.TOKEN
     *
     * @return the value of JH_Auth_Model.TOKEN
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.TOKEN
     *
     * @param token the value for JH_Auth_Model.TOKEN
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.ENCODING_AES_KEY
     *
     * @return the value of JH_Auth_Model.ENCODING_AES_KEY
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getEncodingAesKey() {
        return encodingAesKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.ENCODING_AES_KEY
     *
     * @param encodingAesKey the value for JH_Auth_Model.ENCODING_AES_KEY
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setEncodingAesKey(String encodingAesKey) {
        this.encodingAesKey = encodingAesKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.COM_ID
     *
     * @return the value of JH_Auth_Model.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.COM_ID
     *
     * @param comId the value for JH_Auth_Model.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.DEL_FLG
     *
     * @return the value of JH_Auth_Model.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.DEL_FLG
     *
     * @param delFlg the value for JH_Auth_Model.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.UP_USER
     *
     * @return the value of JH_Auth_Model.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.UP_USER
     *
     * @param upUser the value for JH_Auth_Model.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.UP_DATE
     *
     * @return the value of JH_Auth_Model.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.UP_DATE
     *
     * @param upDate the value for JH_Auth_Model.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.CR_USER
     *
     * @return the value of JH_Auth_Model.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.CR_USER
     *
     * @param crUser the value for JH_Auth_Model.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Model.CR_DATE
     *
     * @return the value of JH_Auth_Model.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Model.CR_DATE
     *
     * @param crDate the value for JH_Auth_Model.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}