package com.odm.oa.dao.pojo;

import java.util.Date;

public class JhAuthExtendmode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendMode.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendMode.TABLE_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendMode.TABLE_FILED_COLUMN
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String tableFiledColumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendMode.TABLE_FILED_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String tableFiledName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendMode.TABLE_FILE_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String tableFileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendMode.DEFAULT_OPTION
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String defaultOption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendMode.DEFAULT_VALUE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String defaultValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendMode.IS_REQUIRE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String isRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendMode.PDID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer pdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendMode.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendMode.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendMode.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendMode.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendMode.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendMode.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendMode.ID
     *
     * @return the value of JH_Auth_ExtendMode.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendMode.ID
     *
     * @param id the value for JH_Auth_ExtendMode.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendMode.TABLE_NAME
     *
     * @return the value of JH_Auth_ExtendMode.TABLE_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendMode.TABLE_NAME
     *
     * @param tableName the value for JH_Auth_ExtendMode.TABLE_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendMode.TABLE_FILED_COLUMN
     *
     * @return the value of JH_Auth_ExtendMode.TABLE_FILED_COLUMN
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getTableFiledColumn() {
        return tableFiledColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendMode.TABLE_FILED_COLUMN
     *
     * @param tableFiledColumn the value for JH_Auth_ExtendMode.TABLE_FILED_COLUMN
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setTableFiledColumn(String tableFiledColumn) {
        this.tableFiledColumn = tableFiledColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendMode.TABLE_FILED_NAME
     *
     * @return the value of JH_Auth_ExtendMode.TABLE_FILED_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getTableFiledName() {
        return tableFiledName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendMode.TABLE_FILED_NAME
     *
     * @param tableFiledName the value for JH_Auth_ExtendMode.TABLE_FILED_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setTableFiledName(String tableFiledName) {
        this.tableFiledName = tableFiledName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendMode.TABLE_FILE_TYPE
     *
     * @return the value of JH_Auth_ExtendMode.TABLE_FILE_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getTableFileType() {
        return tableFileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendMode.TABLE_FILE_TYPE
     *
     * @param tableFileType the value for JH_Auth_ExtendMode.TABLE_FILE_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setTableFileType(String tableFileType) {
        this.tableFileType = tableFileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendMode.DEFAULT_OPTION
     *
     * @return the value of JH_Auth_ExtendMode.DEFAULT_OPTION
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDefaultOption() {
        return defaultOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendMode.DEFAULT_OPTION
     *
     * @param defaultOption the value for JH_Auth_ExtendMode.DEFAULT_OPTION
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDefaultOption(String defaultOption) {
        this.defaultOption = defaultOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendMode.DEFAULT_VALUE
     *
     * @return the value of JH_Auth_ExtendMode.DEFAULT_VALUE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendMode.DEFAULT_VALUE
     *
     * @param defaultValue the value for JH_Auth_ExtendMode.DEFAULT_VALUE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendMode.IS_REQUIRE
     *
     * @return the value of JH_Auth_ExtendMode.IS_REQUIRE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getIsRequire() {
        return isRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendMode.IS_REQUIRE
     *
     * @param isRequire the value for JH_Auth_ExtendMode.IS_REQUIRE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsRequire(String isRequire) {
        this.isRequire = isRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendMode.PDID
     *
     * @return the value of JH_Auth_ExtendMode.PDID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getPdid() {
        return pdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendMode.PDID
     *
     * @param pdid the value for JH_Auth_ExtendMode.PDID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setPdid(Integer pdid) {
        this.pdid = pdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendMode.COM_ID
     *
     * @return the value of JH_Auth_ExtendMode.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendMode.COM_ID
     *
     * @param comId the value for JH_Auth_ExtendMode.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendMode.DEL_FLG
     *
     * @return the value of JH_Auth_ExtendMode.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendMode.DEL_FLG
     *
     * @param delFlg the value for JH_Auth_ExtendMode.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendMode.UP_USER
     *
     * @return the value of JH_Auth_ExtendMode.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendMode.UP_USER
     *
     * @param upUser the value for JH_Auth_ExtendMode.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendMode.UP_DATE
     *
     * @return the value of JH_Auth_ExtendMode.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendMode.UP_DATE
     *
     * @param upDate the value for JH_Auth_ExtendMode.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendMode.CR_USER
     *
     * @return the value of JH_Auth_ExtendMode.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendMode.CR_USER
     *
     * @param crUser the value for JH_Auth_ExtendMode.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendMode.CR_DATE
     *
     * @return the value of JH_Auth_ExtendMode.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendMode.CR_DATE
     *
     * @param crDate the value for JH_Auth_ExtendMode.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}