package com.odm.oa.dao.pojo;

import java.util.Date;

public class JhAuthCollect {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Collect.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Collect.REF_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer refId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Collect.COLLECT_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String collectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Collect.COLLECT_CONTENT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String collectContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Collect.REMARK1
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Collect.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Collect.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Collect.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Collect.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Collect.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Collect.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Collect.ID
     *
     * @return the value of JH_Auth_Collect.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Collect.ID
     *
     * @param id the value for JH_Auth_Collect.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Collect.REF_ID
     *
     * @return the value of JH_Auth_Collect.REF_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Collect.REF_ID
     *
     * @param refId the value for JH_Auth_Collect.REF_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRefId(Integer refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Collect.COLLECT_TYPE
     *
     * @return the value of JH_Auth_Collect.COLLECT_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCollectType() {
        return collectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Collect.COLLECT_TYPE
     *
     * @param collectType the value for JH_Auth_Collect.COLLECT_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCollectType(String collectType) {
        this.collectType = collectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Collect.COLLECT_CONTENT
     *
     * @return the value of JH_Auth_Collect.COLLECT_CONTENT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCollectContent() {
        return collectContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Collect.COLLECT_CONTENT
     *
     * @param collectContent the value for JH_Auth_Collect.COLLECT_CONTENT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCollectContent(String collectContent) {
        this.collectContent = collectContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Collect.REMARK1
     *
     * @return the value of JH_Auth_Collect.REMARK1
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Collect.REMARK1
     *
     * @param remark1 the value for JH_Auth_Collect.REMARK1
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Collect.COM_ID
     *
     * @return the value of JH_Auth_Collect.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Collect.COM_ID
     *
     * @param comId the value for JH_Auth_Collect.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Collect.DEL_FLG
     *
     * @return the value of JH_Auth_Collect.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Collect.DEL_FLG
     *
     * @param delFlg the value for JH_Auth_Collect.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Collect.UP_USER
     *
     * @return the value of JH_Auth_Collect.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Collect.UP_USER
     *
     * @param upUser the value for JH_Auth_Collect.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Collect.UP_DATE
     *
     * @return the value of JH_Auth_Collect.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Collect.UP_DATE
     *
     * @param upDate the value for JH_Auth_Collect.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Collect.CR_USER
     *
     * @return the value of JH_Auth_Collect.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Collect.CR_USER
     *
     * @param crUser the value for JH_Auth_Collect.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Collect.CR_DATE
     *
     * @return the value of JH_Auth_Collect.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Collect.CR_DATE
     *
     * @param crDate the value for JH_Auth_Collect.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}