package com.odm.oa.dao.pojo;

import java.util.Date;

public class JhAuthFunction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Function.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Function.MODEL_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Function.PAGE_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String pageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Function.PAGE_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String pageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Function.ACTION_DATA
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String actionData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Function.IS_INIT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String isInit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Function.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Function.FUN_ORDER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer funOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Function.PAGE_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String pageCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Function.EX_DATA
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String exData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Function.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Function.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Function.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Function.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Function.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Function.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Function.ID
     *
     * @return the value of JH_Auth_Function.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Function.ID
     *
     * @param id the value for JH_Auth_Function.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Function.MODEL_ID
     *
     * @return the value of JH_Auth_Function.MODEL_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Function.MODEL_ID
     *
     * @param modelId the value for JH_Auth_Function.MODEL_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Function.PAGE_NAME
     *
     * @return the value of JH_Auth_Function.PAGE_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getPageName() {
        return pageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Function.PAGE_NAME
     *
     * @param pageName the value for JH_Auth_Function.PAGE_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setPageName(String pageName) {
        this.pageName = pageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Function.PAGE_URL
     *
     * @return the value of JH_Auth_Function.PAGE_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getPageUrl() {
        return pageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Function.PAGE_URL
     *
     * @param pageUrl the value for JH_Auth_Function.PAGE_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setPageUrl(String pageUrl) {
        this.pageUrl = pageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Function.ACTION_DATA
     *
     * @return the value of JH_Auth_Function.ACTION_DATA
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getActionData() {
        return actionData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Function.ACTION_DATA
     *
     * @param actionData the value for JH_Auth_Function.ACTION_DATA
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setActionData(String actionData) {
        this.actionData = actionData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Function.IS_INIT
     *
     * @return the value of JH_Auth_Function.IS_INIT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getIsInit() {
        return isInit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Function.IS_INIT
     *
     * @param isInit the value for JH_Auth_Function.IS_INIT
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsInit(String isInit) {
        this.isInit = isInit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Function.REMARK
     *
     * @return the value of JH_Auth_Function.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Function.REMARK
     *
     * @param remark the value for JH_Auth_Function.REMARK
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Function.FUN_ORDER
     *
     * @return the value of JH_Auth_Function.FUN_ORDER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getFunOrder() {
        return funOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Function.FUN_ORDER
     *
     * @param funOrder the value for JH_Auth_Function.FUN_ORDER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setFunOrder(Integer funOrder) {
        this.funOrder = funOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Function.PAGE_CODE
     *
     * @return the value of JH_Auth_Function.PAGE_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getPageCode() {
        return pageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Function.PAGE_CODE
     *
     * @param pageCode the value for JH_Auth_Function.PAGE_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setPageCode(String pageCode) {
        this.pageCode = pageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Function.EX_DATA
     *
     * @return the value of JH_Auth_Function.EX_DATA
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getExData() {
        return exData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Function.EX_DATA
     *
     * @param exData the value for JH_Auth_Function.EX_DATA
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setExData(String exData) {
        this.exData = exData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Function.COM_ID
     *
     * @return the value of JH_Auth_Function.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Function.COM_ID
     *
     * @param comId the value for JH_Auth_Function.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Function.DEL_FLG
     *
     * @return the value of JH_Auth_Function.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Function.DEL_FLG
     *
     * @param delFlg the value for JH_Auth_Function.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Function.UP_USER
     *
     * @return the value of JH_Auth_Function.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Function.UP_USER
     *
     * @param upUser the value for JH_Auth_Function.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Function.UP_DATE
     *
     * @return the value of JH_Auth_Function.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Function.UP_DATE
     *
     * @param upDate the value for JH_Auth_Function.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Function.CR_USER
     *
     * @return the value of JH_Auth_Function.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Function.CR_USER
     *
     * @param crUser the value for JH_Auth_Function.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Function.CR_DATE
     *
     * @return the value of JH_Auth_Function.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Function.CR_DATE
     *
     * @param crDate the value for JH_Auth_Function.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}