package com.odm.oa.dao.pojo;

import java.util.Date;

public class JhAuthRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Role.ROLE_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Role.ROLE_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Role.ROLE_DEC
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String roleDec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Role.P_ROLE_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer pRoleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Role.DISPLAY_ORDER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer displayOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Role.LEVE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer leve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Role.IS_USE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String isUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Role.IS_SYS_ROLE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String isSysRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Role.WXBQ_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer wxbqCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Role.ROLE_QX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String roleQx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Role.IS_HAS_QX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String isHasQx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Role.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Role.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Role.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Role.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Role.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_Role.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Role.ROLE_CODE
     *
     * @return the value of JH_Auth_Role.ROLE_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Role.ROLE_CODE
     *
     * @param roleCode the value for JH_Auth_Role.ROLE_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRoleCode(Integer roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Role.ROLE_NAME
     *
     * @return the value of JH_Auth_Role.ROLE_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Role.ROLE_NAME
     *
     * @param roleName the value for JH_Auth_Role.ROLE_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Role.ROLE_DEC
     *
     * @return the value of JH_Auth_Role.ROLE_DEC
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRoleDec() {
        return roleDec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Role.ROLE_DEC
     *
     * @param roleDec the value for JH_Auth_Role.ROLE_DEC
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRoleDec(String roleDec) {
        this.roleDec = roleDec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Role.P_ROLE_CODE
     *
     * @return the value of JH_Auth_Role.P_ROLE_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getpRoleCode() {
        return pRoleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Role.P_ROLE_CODE
     *
     * @param pRoleCode the value for JH_Auth_Role.P_ROLE_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setpRoleCode(Integer pRoleCode) {
        this.pRoleCode = pRoleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Role.DISPLAY_ORDER
     *
     * @return the value of JH_Auth_Role.DISPLAY_ORDER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Role.DISPLAY_ORDER
     *
     * @param displayOrder the value for JH_Auth_Role.DISPLAY_ORDER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Role.LEVE
     *
     * @return the value of JH_Auth_Role.LEVE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getLeve() {
        return leve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Role.LEVE
     *
     * @param leve the value for JH_Auth_Role.LEVE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setLeve(Integer leve) {
        this.leve = leve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Role.IS_USE
     *
     * @return the value of JH_Auth_Role.IS_USE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Role.IS_USE
     *
     * @param isUse the value for JH_Auth_Role.IS_USE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsUse(String isUse) {
        this.isUse = isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Role.IS_SYS_ROLE
     *
     * @return the value of JH_Auth_Role.IS_SYS_ROLE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getIsSysRole() {
        return isSysRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Role.IS_SYS_ROLE
     *
     * @param isSysRole the value for JH_Auth_Role.IS_SYS_ROLE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsSysRole(String isSysRole) {
        this.isSysRole = isSysRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Role.WXBQ_CODE
     *
     * @return the value of JH_Auth_Role.WXBQ_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getWxbqCode() {
        return wxbqCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Role.WXBQ_CODE
     *
     * @param wxbqCode the value for JH_Auth_Role.WXBQ_CODE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setWxbqCode(Integer wxbqCode) {
        this.wxbqCode = wxbqCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Role.ROLE_QX
     *
     * @return the value of JH_Auth_Role.ROLE_QX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getRoleQx() {
        return roleQx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Role.ROLE_QX
     *
     * @param roleQx the value for JH_Auth_Role.ROLE_QX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setRoleQx(String roleQx) {
        this.roleQx = roleQx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Role.IS_HAS_QX
     *
     * @return the value of JH_Auth_Role.IS_HAS_QX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getIsHasQx() {
        return isHasQx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Role.IS_HAS_QX
     *
     * @param isHasQx the value for JH_Auth_Role.IS_HAS_QX
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setIsHasQx(String isHasQx) {
        this.isHasQx = isHasQx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Role.COM_ID
     *
     * @return the value of JH_Auth_Role.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Role.COM_ID
     *
     * @param comId the value for JH_Auth_Role.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Role.DEL_FLG
     *
     * @return the value of JH_Auth_Role.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Role.DEL_FLG
     *
     * @param delFlg the value for JH_Auth_Role.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Role.UP_USER
     *
     * @return the value of JH_Auth_Role.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Role.UP_USER
     *
     * @param upUser the value for JH_Auth_Role.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Role.UP_DATE
     *
     * @return the value of JH_Auth_Role.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Role.UP_DATE
     *
     * @param upDate the value for JH_Auth_Role.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Role.CR_USER
     *
     * @return the value of JH_Auth_Role.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Role.CR_USER
     *
     * @param crUser the value for JH_Auth_Role.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_Role.CR_DATE
     *
     * @return the value of JH_Auth_Role.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_Role.CR_DATE
     *
     * @param crDate the value for JH_Auth_Role.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}