package com.odm.oa.dao.pojo;

import java.util.Date;

public class JhAuthExtenddata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendData.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendData.TABLE_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendData.EXTEND_MODE_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer extendModeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendData.DATA_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendData.EXTEND_DATA_VALUE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String extendDataValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendData.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendData.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendData.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendData.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendData.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_ExtendData.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendData.ID
     *
     * @return the value of JH_Auth_ExtendData.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendData.ID
     *
     * @param id the value for JH_Auth_ExtendData.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendData.TABLE_NAME
     *
     * @return the value of JH_Auth_ExtendData.TABLE_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendData.TABLE_NAME
     *
     * @param tableName the value for JH_Auth_ExtendData.TABLE_NAME
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendData.EXTEND_MODE_ID
     *
     * @return the value of JH_Auth_ExtendData.EXTEND_MODE_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getExtendModeId() {
        return extendModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendData.EXTEND_MODE_ID
     *
     * @param extendModeId the value for JH_Auth_ExtendData.EXTEND_MODE_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setExtendModeId(Integer extendModeId) {
        this.extendModeId = extendModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendData.DATA_ID
     *
     * @return the value of JH_Auth_ExtendData.DATA_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendData.DATA_ID
     *
     * @param dataId the value for JH_Auth_ExtendData.DATA_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDataId(Integer dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendData.EXTEND_DATA_VALUE
     *
     * @return the value of JH_Auth_ExtendData.EXTEND_DATA_VALUE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getExtendDataValue() {
        return extendDataValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendData.EXTEND_DATA_VALUE
     *
     * @param extendDataValue the value for JH_Auth_ExtendData.EXTEND_DATA_VALUE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setExtendDataValue(String extendDataValue) {
        this.extendDataValue = extendDataValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendData.COM_ID
     *
     * @return the value of JH_Auth_ExtendData.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendData.COM_ID
     *
     * @param comId the value for JH_Auth_ExtendData.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendData.DEL_FLG
     *
     * @return the value of JH_Auth_ExtendData.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendData.DEL_FLG
     *
     * @param delFlg the value for JH_Auth_ExtendData.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendData.UP_USER
     *
     * @return the value of JH_Auth_ExtendData.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendData.UP_USER
     *
     * @param upUser the value for JH_Auth_ExtendData.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendData.UP_DATE
     *
     * @return the value of JH_Auth_ExtendData.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendData.UP_DATE
     *
     * @param upDate the value for JH_Auth_ExtendData.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendData.CR_USER
     *
     * @return the value of JH_Auth_ExtendData.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendData.CR_USER
     *
     * @param crUser the value for JH_Auth_ExtendData.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_ExtendData.CR_DATE
     *
     * @return the value of JH_Auth_ExtendData.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_ExtendData.CR_DATE
     *
     * @param crDate the value for JH_Auth_ExtendData.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}