package com.odm.oa.dao.pojo;

import java.util.Date;

public class JhAuthQyWxsc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_WXSC.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_WXSC.SD_TEMP
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String sdTemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_WXSC.SC_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String scType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_WXSC.SC_PIC_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String scPicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_WXSC.SC_FILE_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String scFileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_WXSC.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_WXSC.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_WXSC.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String upUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_WXSC.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_WXSC.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JH_Auth_QY_WXSC.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    private Date crDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_WXSC.ID
     *
     * @return the value of JH_Auth_QY_WXSC.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_WXSC.ID
     *
     * @param id the value for JH_Auth_QY_WXSC.ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_WXSC.SD_TEMP
     *
     * @return the value of JH_Auth_QY_WXSC.SD_TEMP
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getSdTemp() {
        return sdTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_WXSC.SD_TEMP
     *
     * @param sdTemp the value for JH_Auth_QY_WXSC.SD_TEMP
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setSdTemp(String sdTemp) {
        this.sdTemp = sdTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_WXSC.SC_TYPE
     *
     * @return the value of JH_Auth_QY_WXSC.SC_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getScType() {
        return scType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_WXSC.SC_TYPE
     *
     * @param scType the value for JH_Auth_QY_WXSC.SC_TYPE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setScType(String scType) {
        this.scType = scType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_WXSC.SC_PIC_URL
     *
     * @return the value of JH_Auth_QY_WXSC.SC_PIC_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getScPicUrl() {
        return scPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_WXSC.SC_PIC_URL
     *
     * @param scPicUrl the value for JH_Auth_QY_WXSC.SC_PIC_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setScPicUrl(String scPicUrl) {
        this.scPicUrl = scPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_WXSC.SC_FILE_URL
     *
     * @return the value of JH_Auth_QY_WXSC.SC_FILE_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getScFileUrl() {
        return scFileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_WXSC.SC_FILE_URL
     *
     * @param scFileUrl the value for JH_Auth_QY_WXSC.SC_FILE_URL
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setScFileUrl(String scFileUrl) {
        this.scFileUrl = scFileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_WXSC.COM_ID
     *
     * @return the value of JH_Auth_QY_WXSC.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_WXSC.COM_ID
     *
     * @param comId the value for JH_Auth_QY_WXSC.COM_ID
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_WXSC.DEL_FLG
     *
     * @return the value of JH_Auth_QY_WXSC.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_WXSC.DEL_FLG
     *
     * @param delFlg the value for JH_Auth_QY_WXSC.DEL_FLG
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_WXSC.UP_USER
     *
     * @return the value of JH_Auth_QY_WXSC.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getUpUser() {
        return upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_WXSC.UP_USER
     *
     * @param upUser the value for JH_Auth_QY_WXSC.UP_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpUser(String upUser) {
        this.upUser = upUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_WXSC.UP_DATE
     *
     * @return the value of JH_Auth_QY_WXSC.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_WXSC.UP_DATE
     *
     * @param upDate the value for JH_Auth_QY_WXSC.UP_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_WXSC.CR_USER
     *
     * @return the value of JH_Auth_QY_WXSC.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_WXSC.CR_USER
     *
     * @param crUser the value for JH_Auth_QY_WXSC.CR_USER
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JH_Auth_QY_WXSC.CR_DATE
     *
     * @return the value of JH_Auth_QY_WXSC.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JH_Auth_QY_WXSC.CR_DATE
     *
     * @param crDate the value for JH_Auth_QY_WXSC.CR_DATE
     *
     * @mbggenerated Sat Jul 14 20:25:19 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }
}