package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.CrmCustomerInfo;
import java.util.List;

public interface CrmCustomerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_info
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_info
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    int insert(CrmCustomerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_info
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    CrmCustomerInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_info
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    List<CrmCustomerInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_info
     *
     * @mbggenerated Fri Jul 20 11:17:57 CST 2018
     */
    int updateByPrimaryKey(CrmCustomerInfo record);
}