package com.odm.oa.dao.mapper;

import java.util.List;

import com.odm.oa.dao.pojo.FtFile;

public interface FtFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int insert(FtFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    FtFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    List<FtFile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int updateByPrimaryKey(FtFile record);

	List<FtFile> selectCFileByPId(Integer id);




}