package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.FtFileUsertag;
import java.util.List;

public interface FtFileUsertagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File_UserTag
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File_UserTag
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int insert(FtFileUsertag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File_UserTag
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    FtFileUsertag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File_UserTag
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    List<FtFileUsertag> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File_UserTag
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int updateByPrimaryKey(FtFileUsertag record);
}