package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.FtFileVesion;
import java.util.List;

public interface FtFileVesionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File_Vesion
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File_Vesion
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int insert(FtFileVesion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File_Vesion
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    FtFileVesion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File_Vesion
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    List<FtFileVesion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_File_Vesion
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int updateByPrimaryKey(FtFileVesion record);
}