package com.odm.oa.dao.mapper;

import java.util.List;

import com.odm.oa.dao.pojo.FtFolder;
import com.odm.oa.dao.pojo.pagination.DocPagination;

public interface FtFolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_Folder
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_Folder
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int insert(FtFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_Folder
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    FtFolder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_Folder
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    List<FtFolder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FT_Folder
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int updateByPrimaryKey(FtFolder record);

	List<FtFolder> pageList(DocPagination p);

	List<FtFolder> selectByPId(Integer id);

	List<FtFolder> selectRootDir(DocPagination request);

	List<FtFolder> selectShareRootDir(DocPagination request);

	FtFolder selectByName(String name);
}