package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.JhAuthUsercustomdata;
import java.util.List;

public interface JhAuthUsercustomdataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_UserCustomData
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_UserCustomData
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int insert(JhAuthUsercustomdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_UserCustomData
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    JhAuthUsercustomdata selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_UserCustomData
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    List<JhAuthUsercustomdata> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_UserCustomData
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int updateByPrimaryKey(JhAuthUsercustomdata record);
}