package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.JhAuthRole;
import java.util.List;

public interface JhAuthRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Role
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int deleteByPrimaryKey(Integer rolecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Role
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int insert(JhAuthRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Role
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    JhAuthRole selectByPrimaryKey(Integer rolecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Role
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    List<JhAuthRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Role
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int updateByPrimaryKey(JhAuthRole record);
}