package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.JhAuthGuanzhu;
import java.util.List;

public interface JhAuthGuanzhuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_GUANZHU
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_GUANZHU
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int insert(JhAuthGuanzhu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_GUANZHU
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    JhAuthGuanzhu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_GUANZHU
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    List<JhAuthGuanzhu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_GUANZHU
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int updateByPrimaryKey(JhAuthGuanzhu record);
}