package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.JhAuthQy;
import java.util.List;

public interface JhAuthQyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_QY
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int deleteByPrimaryKey(Integer comid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_QY
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int insert(JhAuthQy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_QY
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    JhAuthQy selectByPrimaryKey(Integer comid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_QY
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    List<JhAuthQy> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_QY
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int updateByPrimaryKey(JhAuthQy record);
}