package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.JhAuthUserCenter;
import java.util.List;

public interface JhAuthUserCenterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_User_Center
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_User_Center
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int insert(JhAuthUserCenter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_User_Center
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    JhAuthUserCenter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_User_Center
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    List<JhAuthUserCenter> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_User_Center
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int updateByPrimaryKey(JhAuthUserCenter record);
}