package com.odm.oa.dao.mapper;

import java.util.List;

import com.odm.oa.dao.pojo.JhAuthBranch;
import com.odm.oa.dao.pojo.ex.JhAuthBranchEx;
import com.odm.oa.dao.pojo.pagination.JhAuthBranchPagination;

public interface JhAuthBranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Branch
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int deleteByPrimaryKey(Integer deptcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Branch
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int insert(JhAuthBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Branch
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    JhAuthBranch selectByPrimaryKey(Integer deptcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Branch
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    List<JhAuthBranch> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_Branch
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int updateByPrimaryKey(JhAuthBranch record);

	/**
	 * 部门列表展示
	 *
	 * @param request
	 * @return
	 */
	List<JhAuthBranchEx> paginationBranch(JhAuthBranchPagination request);

	/**
	 * 重复名称检验
	 * 
	 * @param depeName
	 * @return
	 */
	JhAuthBranch selectByName(String depeName);

	/**
	 * 父部门列表
	 * 
	 * @return
	 */
	List<JhAuthBranch> selectDeptRoot();
}