package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.JhAuthExtendmode;
import java.util.List;

public interface JhAuthExtendmodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_ExtendMode
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_ExtendMode
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int insert(JhAuthExtendmode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_ExtendMode
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    JhAuthExtendmode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_ExtendMode
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    List<JhAuthExtendmode> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_ExtendMode
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int updateByPrimaryKey(JhAuthExtendmode record);
}