package com.odm.oa.dao.mapper;

import java.util.List;

import com.odm.oa.dao.pojo.JhAuthUser;
import com.odm.oa.dao.pojo.ex.JhAuthUserEx;

public interface JhAuthUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_User
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_User
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int insert(JhAuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_User
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    JhAuthUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_User
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    List<JhAuthUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_User
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int updateByPrimaryKey(JhAuthUser record);

	/**
	 * @param param
	 * @return
	 */
	JhAuthUserEx selectUserByUserName(String userName);

	/**
	 * 部门管理查询
	 * 
	 * @param deptCode
	 * @return
	 */
	List<JhAuthUserEx> selectUsersByDeptCode(Integer deptCode);
}