package com.odm.oa.dao.mapper;

import com.odm.oa.dao.pojo.JhAuthQyModel;
import java.util.List;

public interface JhAuthQyModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_QY_Model
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_QY_Model
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int insert(JhAuthQyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_QY_Model
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    JhAuthQyModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_QY_Model
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    List<JhAuthQyModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JH_Auth_QY_Model
     *
     * @mbggenerated Tue Jul 10 00:35:47 CST 2018
     */
    int updateByPrimaryKey(JhAuthQyModel record);
}